// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module get3DImageIndex (
        ap_ready,
        layer,
        roll,
        strip,
        ap_return
);


output   ap_ready;
input  [3:0] layer;
input  [10:0] roll;
input  [10:0] strip;
output  [15:0] ap_return;

wire   [2:0] trunc_ln15_fu_44_p1;
wire   [14:0] shl_ln_fu_48_p3;
wire   [12:0] shl_ln15_1_fu_60_p3;
wire   [15:0] zext_ln15_fu_56_p1;
wire   [15:0] zext_ln15_1_fu_68_p1;
wire   [3:0] trunc_ln15_1_fu_78_p1;
wire   [10:0] shl_ln15_fu_90_p2;
wire   [12:0] shl_ln15_2_fu_82_p3;
wire   [12:0] zext_ln15_2_fu_96_p1;
wire   [12:0] sub_ln15_1_fu_100_p2;
wire   [15:0] sub_ln15_fu_72_p2;
wire  signed [15:0] sext_ln15_fu_106_p1;
wire   [15:0] add_ln15_fu_110_p2;
wire   [15:0] add_ln15_1_fu_116_p2;
wire   [15:0] zext_ln15_3_fu_122_p1;

assign add_ln15_1_fu_116_p2 = ($signed(sext_ln15_fu_106_p1) + $signed(add_ln15_fu_110_p2));

assign add_ln15_fu_110_p2 = ($signed(16'd62079) + $signed(sub_ln15_fu_72_p2));

assign ap_ready = 1'b1;

assign ap_return = (add_ln15_1_fu_116_p2 + zext_ln15_3_fu_122_p1);

assign sext_ln15_fu_106_p1 = $signed(sub_ln15_1_fu_100_p2);

assign shl_ln15_1_fu_60_p3 = {{trunc_ln15_fu_44_p1}, {10'd0}};

assign shl_ln15_2_fu_82_p3 = {{trunc_ln15_1_fu_78_p1}, {9'd0}};

assign shl_ln15_fu_90_p2 = roll << 11'd7;

assign shl_ln_fu_48_p3 = {{trunc_ln15_fu_44_p1}, {12'd0}};

assign sub_ln15_1_fu_100_p2 = (shl_ln15_2_fu_82_p3 - zext_ln15_2_fu_96_p1);

assign sub_ln15_fu_72_p2 = (zext_ln15_fu_56_p1 - zext_ln15_1_fu_68_p1);

assign trunc_ln15_1_fu_78_p1 = roll[3:0];

assign trunc_ln15_fu_44_p1 = layer[2:0];

assign zext_ln15_1_fu_68_p1 = shl_ln15_1_fu_60_p3;

assign zext_ln15_2_fu_96_p1 = shl_ln15_fu_90_p2;

assign zext_ln15_3_fu_122_p1 = strip;

assign zext_ln15_fu_56_p1 = shl_ln_fu_48_p3;

endmodule //get3DImageIndex
