// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        data_32_V_read,
        data_33_V_read,
        data_34_V_read,
        data_35_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] data_0_V_read;
input  [11:0] data_1_V_read;
input  [11:0] data_2_V_read;
input  [11:0] data_3_V_read;
input  [11:0] data_4_V_read;
input  [11:0] data_5_V_read;
input  [11:0] data_6_V_read;
input  [11:0] data_7_V_read;
input  [11:0] data_8_V_read;
input  [11:0] data_9_V_read;
input  [11:0] data_10_V_read;
input  [11:0] data_11_V_read;
input  [11:0] data_12_V_read;
input  [11:0] data_13_V_read;
input  [11:0] data_14_V_read;
input  [11:0] data_15_V_read;
input  [11:0] data_16_V_read;
input  [11:0] data_17_V_read;
input  [11:0] data_18_V_read;
input  [11:0] data_19_V_read;
input  [11:0] data_20_V_read;
input  [11:0] data_21_V_read;
input  [11:0] data_22_V_read;
input  [11:0] data_23_V_read;
input  [11:0] data_24_V_read;
input  [11:0] data_25_V_read;
input  [11:0] data_26_V_read;
input  [11:0] data_27_V_read;
input  [11:0] data_28_V_read;
input  [11:0] data_29_V_read;
input  [11:0] data_30_V_read;
input  [11:0] data_31_V_read;
input  [11:0] data_32_V_read;
input  [11:0] data_33_V_read;
input  [11:0] data_34_V_read;
input  [11:0] data_35_V_read;
output  [10:0] ap_return_0;
output  [10:0] ap_return_1;
output  [10:0] ap_return_2;
output  [10:0] ap_return_3;
output  [10:0] ap_return_4;
output  [10:0] ap_return_5;
output  [10:0] ap_return_6;
output  [10:0] ap_return_7;
output  [10:0] ap_return_8;
output  [10:0] ap_return_9;
output  [10:0] ap_return_10;
output  [10:0] ap_return_11;
output  [10:0] ap_return_12;
output  [10:0] ap_return_13;
output  [10:0] ap_return_14;
output  [10:0] ap_return_15;
output  [10:0] ap_return_16;
output  [10:0] ap_return_17;
output  [10:0] ap_return_18;
output  [10:0] ap_return_19;
output  [10:0] ap_return_20;
output  [10:0] ap_return_21;
output  [10:0] ap_return_22;
output  [10:0] ap_return_23;
output  [10:0] ap_return_24;
output  [10:0] ap_return_25;
output  [10:0] ap_return_26;
output  [10:0] ap_return_27;
output  [10:0] ap_return_28;
output  [10:0] ap_return_29;
output  [10:0] ap_return_30;
output  [10:0] ap_return_31;
output  [10:0] ap_return_32;
output  [10:0] ap_return_33;
output  [10:0] ap_return_34;
output  [10:0] ap_return_35;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[10:0] ap_return_0;
reg[10:0] ap_return_1;
reg[10:0] ap_return_2;
reg[10:0] ap_return_3;
reg[10:0] ap_return_4;
reg[10:0] ap_return_5;
reg[10:0] ap_return_6;
reg[10:0] ap_return_7;
reg[10:0] ap_return_8;
reg[10:0] ap_return_9;
reg[10:0] ap_return_10;
reg[10:0] ap_return_11;
reg[10:0] ap_return_12;
reg[10:0] ap_return_13;
reg[10:0] ap_return_14;
reg[10:0] ap_return_15;
reg[10:0] ap_return_16;
reg[10:0] ap_return_17;
reg[10:0] ap_return_18;
reg[10:0] ap_return_19;
reg[10:0] ap_return_20;
reg[10:0] ap_return_21;
reg[10:0] ap_return_22;
reg[10:0] ap_return_23;
reg[10:0] ap_return_24;
reg[10:0] ap_return_25;
reg[10:0] ap_return_26;
reg[10:0] ap_return_27;
reg[10:0] ap_return_28;
reg[10:0] ap_return_29;
reg[10:0] ap_return_30;
reg[10:0] ap_return_31;
reg[10:0] ap_return_32;
reg[10:0] ap_return_33;
reg[10:0] ap_return_34;
reg[10:0] ap_return_35;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1;
wire   [0:0] icmp_ln1494_fu_316_p2;
wire   [10:0] trunc_ln1494_fu_312_p1;
wire   [0:0] icmp_ln1494_1_fu_334_p2;
wire   [10:0] trunc_ln1494_1_fu_330_p1;
wire   [0:0] icmp_ln1494_2_fu_352_p2;
wire   [10:0] trunc_ln1494_2_fu_348_p1;
wire   [0:0] icmp_ln1494_3_fu_370_p2;
wire   [10:0] trunc_ln1494_3_fu_366_p1;
wire   [0:0] icmp_ln1494_4_fu_388_p2;
wire   [10:0] trunc_ln1494_4_fu_384_p1;
wire   [0:0] icmp_ln1494_5_fu_406_p2;
wire   [10:0] trunc_ln1494_5_fu_402_p1;
wire   [0:0] icmp_ln1494_6_fu_424_p2;
wire   [10:0] trunc_ln1494_6_fu_420_p1;
wire   [0:0] icmp_ln1494_7_fu_442_p2;
wire   [10:0] trunc_ln1494_7_fu_438_p1;
wire   [0:0] icmp_ln1494_8_fu_460_p2;
wire   [10:0] trunc_ln1494_8_fu_456_p1;
wire   [0:0] icmp_ln1494_9_fu_478_p2;
wire   [10:0] trunc_ln1494_9_fu_474_p1;
wire   [0:0] icmp_ln1494_10_fu_496_p2;
wire   [10:0] trunc_ln1494_10_fu_492_p1;
wire   [0:0] icmp_ln1494_11_fu_514_p2;
wire   [10:0] trunc_ln1494_11_fu_510_p1;
wire   [0:0] icmp_ln1494_12_fu_532_p2;
wire   [10:0] trunc_ln1494_12_fu_528_p1;
wire   [0:0] icmp_ln1494_13_fu_550_p2;
wire   [10:0] trunc_ln1494_13_fu_546_p1;
wire   [0:0] icmp_ln1494_14_fu_568_p2;
wire   [10:0] trunc_ln1494_14_fu_564_p1;
wire   [0:0] icmp_ln1494_15_fu_586_p2;
wire   [10:0] trunc_ln1494_15_fu_582_p1;
wire   [0:0] icmp_ln1494_16_fu_604_p2;
wire   [10:0] trunc_ln1494_16_fu_600_p1;
wire   [0:0] icmp_ln1494_17_fu_622_p2;
wire   [10:0] trunc_ln1494_17_fu_618_p1;
wire   [0:0] icmp_ln1494_18_fu_640_p2;
wire   [10:0] trunc_ln1494_18_fu_636_p1;
wire   [0:0] icmp_ln1494_19_fu_658_p2;
wire   [10:0] trunc_ln1494_19_fu_654_p1;
wire   [0:0] icmp_ln1494_20_fu_676_p2;
wire   [10:0] trunc_ln1494_20_fu_672_p1;
wire   [0:0] icmp_ln1494_21_fu_694_p2;
wire   [10:0] trunc_ln1494_21_fu_690_p1;
wire   [0:0] icmp_ln1494_22_fu_712_p2;
wire   [10:0] trunc_ln1494_22_fu_708_p1;
wire   [0:0] icmp_ln1494_23_fu_730_p2;
wire   [10:0] trunc_ln1494_23_fu_726_p1;
wire   [0:0] icmp_ln1494_24_fu_748_p2;
wire   [10:0] trunc_ln1494_24_fu_744_p1;
wire   [0:0] icmp_ln1494_25_fu_766_p2;
wire   [10:0] trunc_ln1494_25_fu_762_p1;
wire   [0:0] icmp_ln1494_26_fu_784_p2;
wire   [10:0] trunc_ln1494_26_fu_780_p1;
wire   [0:0] icmp_ln1494_27_fu_802_p2;
wire   [10:0] trunc_ln1494_27_fu_798_p1;
wire   [0:0] icmp_ln1494_28_fu_820_p2;
wire   [10:0] trunc_ln1494_28_fu_816_p1;
wire   [0:0] icmp_ln1494_29_fu_838_p2;
wire   [10:0] trunc_ln1494_29_fu_834_p1;
wire   [0:0] icmp_ln1494_30_fu_856_p2;
wire   [10:0] trunc_ln1494_30_fu_852_p1;
wire   [0:0] icmp_ln1494_31_fu_874_p2;
wire   [10:0] trunc_ln1494_31_fu_870_p1;
wire   [0:0] icmp_ln1494_32_fu_892_p2;
wire   [10:0] trunc_ln1494_32_fu_888_p1;
wire   [0:0] icmp_ln1494_33_fu_910_p2;
wire   [10:0] trunc_ln1494_33_fu_906_p1;
wire   [0:0] icmp_ln1494_34_fu_928_p2;
wire   [10:0] trunc_ln1494_34_fu_924_p1;
wire   [0:0] icmp_ln1494_35_fu_946_p2;
wire   [10:0] trunc_ln1494_35_fu_942_p1;
wire   [10:0] select_ln81_fu_322_p3;
wire   [10:0] select_ln81_1_fu_340_p3;
wire   [10:0] select_ln81_2_fu_358_p3;
wire   [10:0] select_ln81_3_fu_376_p3;
wire   [10:0] select_ln81_4_fu_394_p3;
wire   [10:0] select_ln81_5_fu_412_p3;
wire   [10:0] select_ln81_6_fu_430_p3;
wire   [10:0] select_ln81_7_fu_448_p3;
wire   [10:0] select_ln81_8_fu_466_p3;
wire   [10:0] select_ln81_9_fu_484_p3;
wire   [10:0] select_ln81_10_fu_502_p3;
wire   [10:0] select_ln81_11_fu_520_p3;
wire   [10:0] select_ln81_12_fu_538_p3;
wire   [10:0] select_ln81_13_fu_556_p3;
wire   [10:0] select_ln81_14_fu_574_p3;
wire   [10:0] select_ln81_15_fu_592_p3;
wire   [10:0] select_ln81_16_fu_610_p3;
wire   [10:0] select_ln81_17_fu_628_p3;
wire   [10:0] select_ln81_18_fu_646_p3;
wire   [10:0] select_ln81_19_fu_664_p3;
wire   [10:0] select_ln81_20_fu_682_p3;
wire   [10:0] select_ln81_21_fu_700_p3;
wire   [10:0] select_ln81_22_fu_718_p3;
wire   [10:0] select_ln81_23_fu_736_p3;
wire   [10:0] select_ln81_24_fu_754_p3;
wire   [10:0] select_ln81_25_fu_772_p3;
wire   [10:0] select_ln81_26_fu_790_p3;
wire   [10:0] select_ln81_27_fu_808_p3;
wire   [10:0] select_ln81_28_fu_826_p3;
wire   [10:0] select_ln81_29_fu_844_p3;
wire   [10:0] select_ln81_30_fu_862_p3;
wire   [10:0] select_ln81_31_fu_880_p3;
wire   [10:0] select_ln81_32_fu_898_p3;
wire   [10:0] select_ln81_33_fu_916_p3;
wire   [10:0] select_ln81_34_fu_934_p3;
wire   [10:0] select_ln81_35_fu_952_p3;
reg   [10:0] ap_return_0_preg;
reg   [10:0] ap_return_1_preg;
reg   [10:0] ap_return_2_preg;
reg   [10:0] ap_return_3_preg;
reg   [10:0] ap_return_4_preg;
reg   [10:0] ap_return_5_preg;
reg   [10:0] ap_return_6_preg;
reg   [10:0] ap_return_7_preg;
reg   [10:0] ap_return_8_preg;
reg   [10:0] ap_return_9_preg;
reg   [10:0] ap_return_10_preg;
reg   [10:0] ap_return_11_preg;
reg   [10:0] ap_return_12_preg;
reg   [10:0] ap_return_13_preg;
reg   [10:0] ap_return_14_preg;
reg   [10:0] ap_return_15_preg;
reg   [10:0] ap_return_16_preg;
reg   [10:0] ap_return_17_preg;
reg   [10:0] ap_return_18_preg;
reg   [10:0] ap_return_19_preg;
reg   [10:0] ap_return_20_preg;
reg   [10:0] ap_return_21_preg;
reg   [10:0] ap_return_22_preg;
reg   [10:0] ap_return_23_preg;
reg   [10:0] ap_return_24_preg;
reg   [10:0] ap_return_25_preg;
reg   [10:0] ap_return_26_preg;
reg   [10:0] ap_return_27_preg;
reg   [10:0] ap_return_28_preg;
reg   [10:0] ap_return_29_preg;
reg   [10:0] ap_return_30_preg;
reg   [10:0] ap_return_31_preg;
reg   [10:0] ap_return_32_preg;
reg   [10:0] ap_return_33_preg;
reg   [10:0] ap_return_34_preg;
reg   [10:0] ap_return_35_preg;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_return_0_preg = 11'd0;
#0 ap_return_1_preg = 11'd0;
#0 ap_return_2_preg = 11'd0;
#0 ap_return_3_preg = 11'd0;
#0 ap_return_4_preg = 11'd0;
#0 ap_return_5_preg = 11'd0;
#0 ap_return_6_preg = 11'd0;
#0 ap_return_7_preg = 11'd0;
#0 ap_return_8_preg = 11'd0;
#0 ap_return_9_preg = 11'd0;
#0 ap_return_10_preg = 11'd0;
#0 ap_return_11_preg = 11'd0;
#0 ap_return_12_preg = 11'd0;
#0 ap_return_13_preg = 11'd0;
#0 ap_return_14_preg = 11'd0;
#0 ap_return_15_preg = 11'd0;
#0 ap_return_16_preg = 11'd0;
#0 ap_return_17_preg = 11'd0;
#0 ap_return_18_preg = 11'd0;
#0 ap_return_19_preg = 11'd0;
#0 ap_return_20_preg = 11'd0;
#0 ap_return_21_preg = 11'd0;
#0 ap_return_22_preg = 11'd0;
#0 ap_return_23_preg = 11'd0;
#0 ap_return_24_preg = 11'd0;
#0 ap_return_25_preg = 11'd0;
#0 ap_return_26_preg = 11'd0;
#0 ap_return_27_preg = 11'd0;
#0 ap_return_28_preg = 11'd0;
#0 ap_return_29_preg = 11'd0;
#0 ap_return_30_preg = 11'd0;
#0 ap_return_31_preg = 11'd0;
#0 ap_return_32_preg = 11'd0;
#0 ap_return_33_preg = 11'd0;
#0 ap_return_34_preg = 11'd0;
#0 ap_return_35_preg = 11'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= select_ln81_fu_322_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_10_preg <= select_ln81_10_fu_502_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_11_preg <= select_ln81_11_fu_520_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_12_preg <= select_ln81_12_fu_538_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_13_preg <= select_ln81_13_fu_556_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_14_preg <= select_ln81_14_fu_574_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_15_preg <= select_ln81_15_fu_592_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_16_preg <= select_ln81_16_fu_610_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_17_preg <= select_ln81_17_fu_628_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_18_preg <= select_ln81_18_fu_646_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_19_preg <= select_ln81_19_fu_664_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= select_ln81_1_fu_340_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_20_preg <= select_ln81_20_fu_682_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_21_preg <= select_ln81_21_fu_700_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_22_preg <= select_ln81_22_fu_718_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_23_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_23_preg <= select_ln81_23_fu_736_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_24_preg <= select_ln81_24_fu_754_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_25_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_25_preg <= select_ln81_25_fu_772_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_26_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_26_preg <= select_ln81_26_fu_790_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_27_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_27_preg <= select_ln81_27_fu_808_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_28_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_28_preg <= select_ln81_28_fu_826_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_29_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_29_preg <= select_ln81_29_fu_844_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= select_ln81_2_fu_358_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_30_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_30_preg <= select_ln81_30_fu_862_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_31_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_31_preg <= select_ln81_31_fu_880_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_32_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_32_preg <= select_ln81_32_fu_898_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_33_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_33_preg <= select_ln81_33_fu_916_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_34_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_34_preg <= select_ln81_34_fu_934_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_35_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_35_preg <= select_ln81_35_fu_952_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= select_ln81_3_fu_376_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= select_ln81_4_fu_394_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= select_ln81_5_fu_412_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= select_ln81_6_fu_430_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= select_ln81_7_fu_448_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_8_preg <= select_ln81_8_fu_466_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 11'd0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_9_preg <= select_ln81_9_fu_484_p3;
        end
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = select_ln81_fu_322_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = select_ln81_1_fu_340_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_10 = select_ln81_10_fu_502_p3;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_11 = select_ln81_11_fu_520_p3;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_12 = select_ln81_12_fu_538_p3;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_13 = select_ln81_13_fu_556_p3;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_14 = select_ln81_14_fu_574_p3;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_15 = select_ln81_15_fu_592_p3;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_16 = select_ln81_16_fu_610_p3;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_17 = select_ln81_17_fu_628_p3;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_18 = select_ln81_18_fu_646_p3;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_19 = select_ln81_19_fu_664_p3;
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = select_ln81_2_fu_358_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_20 = select_ln81_20_fu_682_p3;
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_21 = select_ln81_21_fu_700_p3;
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_22 = select_ln81_22_fu_718_p3;
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_23 = select_ln81_23_fu_736_p3;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_24 = select_ln81_24_fu_754_p3;
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_25 = select_ln81_25_fu_772_p3;
    end else begin
        ap_return_25 = ap_return_25_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_26 = select_ln81_26_fu_790_p3;
    end else begin
        ap_return_26 = ap_return_26_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_27 = select_ln81_27_fu_808_p3;
    end else begin
        ap_return_27 = ap_return_27_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_28 = select_ln81_28_fu_826_p3;
    end else begin
        ap_return_28 = ap_return_28_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_29 = select_ln81_29_fu_844_p3;
    end else begin
        ap_return_29 = ap_return_29_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = select_ln81_3_fu_376_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_30 = select_ln81_30_fu_862_p3;
    end else begin
        ap_return_30 = ap_return_30_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_31 = select_ln81_31_fu_880_p3;
    end else begin
        ap_return_31 = ap_return_31_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_32 = select_ln81_32_fu_898_p3;
    end else begin
        ap_return_32 = ap_return_32_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_33 = select_ln81_33_fu_916_p3;
    end else begin
        ap_return_33 = ap_return_33_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_34 = select_ln81_34_fu_934_p3;
    end else begin
        ap_return_34 = ap_return_34_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_35 = select_ln81_35_fu_952_p3;
    end else begin
        ap_return_35 = ap_return_35_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = select_ln81_4_fu_394_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = select_ln81_5_fu_412_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = select_ln81_6_fu_430_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = select_ln81_7_fu_448_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_8 = select_ln81_8_fu_466_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_9 = select_ln81_9_fu_484_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign icmp_ln1494_10_fu_496_p2 = (($signed(data_10_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_514_p2 = (($signed(data_11_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_532_p2 = (($signed(data_12_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_550_p2 = (($signed(data_13_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_568_p2 = (($signed(data_14_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_586_p2 = (($signed(data_15_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_604_p2 = (($signed(data_16_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_622_p2 = (($signed(data_17_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_640_p2 = (($signed(data_18_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_658_p2 = (($signed(data_19_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_334_p2 = (($signed(data_1_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_20_fu_676_p2 = (($signed(data_20_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_21_fu_694_p2 = (($signed(data_21_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_22_fu_712_p2 = (($signed(data_22_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_23_fu_730_p2 = (($signed(data_23_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_24_fu_748_p2 = (($signed(data_24_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_25_fu_766_p2 = (($signed(data_25_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_26_fu_784_p2 = (($signed(data_26_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_27_fu_802_p2 = (($signed(data_27_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_28_fu_820_p2 = (($signed(data_28_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_29_fu_838_p2 = (($signed(data_29_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_352_p2 = (($signed(data_2_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_30_fu_856_p2 = (($signed(data_30_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_31_fu_874_p2 = (($signed(data_31_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_32_fu_892_p2 = (($signed(data_32_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_33_fu_910_p2 = (($signed(data_33_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_34_fu_928_p2 = (($signed(data_34_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_35_fu_946_p2 = (($signed(data_35_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_370_p2 = (($signed(data_3_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_388_p2 = (($signed(data_4_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_406_p2 = (($signed(data_5_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_424_p2 = (($signed(data_6_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_442_p2 = (($signed(data_7_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_460_p2 = (($signed(data_8_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_478_p2 = (($signed(data_9_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_316_p2 = (($signed(data_0_V_read) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign select_ln81_10_fu_502_p3 = ((icmp_ln1494_10_fu_496_p2[0:0] === 1'b1) ? trunc_ln1494_10_fu_492_p1 : 11'd0);

assign select_ln81_11_fu_520_p3 = ((icmp_ln1494_11_fu_514_p2[0:0] === 1'b1) ? trunc_ln1494_11_fu_510_p1 : 11'd0);

assign select_ln81_12_fu_538_p3 = ((icmp_ln1494_12_fu_532_p2[0:0] === 1'b1) ? trunc_ln1494_12_fu_528_p1 : 11'd0);

assign select_ln81_13_fu_556_p3 = ((icmp_ln1494_13_fu_550_p2[0:0] === 1'b1) ? trunc_ln1494_13_fu_546_p1 : 11'd0);

assign select_ln81_14_fu_574_p3 = ((icmp_ln1494_14_fu_568_p2[0:0] === 1'b1) ? trunc_ln1494_14_fu_564_p1 : 11'd0);

assign select_ln81_15_fu_592_p3 = ((icmp_ln1494_15_fu_586_p2[0:0] === 1'b1) ? trunc_ln1494_15_fu_582_p1 : 11'd0);

assign select_ln81_16_fu_610_p3 = ((icmp_ln1494_16_fu_604_p2[0:0] === 1'b1) ? trunc_ln1494_16_fu_600_p1 : 11'd0);

assign select_ln81_17_fu_628_p3 = ((icmp_ln1494_17_fu_622_p2[0:0] === 1'b1) ? trunc_ln1494_17_fu_618_p1 : 11'd0);

assign select_ln81_18_fu_646_p3 = ((icmp_ln1494_18_fu_640_p2[0:0] === 1'b1) ? trunc_ln1494_18_fu_636_p1 : 11'd0);

assign select_ln81_19_fu_664_p3 = ((icmp_ln1494_19_fu_658_p2[0:0] === 1'b1) ? trunc_ln1494_19_fu_654_p1 : 11'd0);

assign select_ln81_1_fu_340_p3 = ((icmp_ln1494_1_fu_334_p2[0:0] === 1'b1) ? trunc_ln1494_1_fu_330_p1 : 11'd0);

assign select_ln81_20_fu_682_p3 = ((icmp_ln1494_20_fu_676_p2[0:0] === 1'b1) ? trunc_ln1494_20_fu_672_p1 : 11'd0);

assign select_ln81_21_fu_700_p3 = ((icmp_ln1494_21_fu_694_p2[0:0] === 1'b1) ? trunc_ln1494_21_fu_690_p1 : 11'd0);

assign select_ln81_22_fu_718_p3 = ((icmp_ln1494_22_fu_712_p2[0:0] === 1'b1) ? trunc_ln1494_22_fu_708_p1 : 11'd0);

assign select_ln81_23_fu_736_p3 = ((icmp_ln1494_23_fu_730_p2[0:0] === 1'b1) ? trunc_ln1494_23_fu_726_p1 : 11'd0);

assign select_ln81_24_fu_754_p3 = ((icmp_ln1494_24_fu_748_p2[0:0] === 1'b1) ? trunc_ln1494_24_fu_744_p1 : 11'd0);

assign select_ln81_25_fu_772_p3 = ((icmp_ln1494_25_fu_766_p2[0:0] === 1'b1) ? trunc_ln1494_25_fu_762_p1 : 11'd0);

assign select_ln81_26_fu_790_p3 = ((icmp_ln1494_26_fu_784_p2[0:0] === 1'b1) ? trunc_ln1494_26_fu_780_p1 : 11'd0);

assign select_ln81_27_fu_808_p3 = ((icmp_ln1494_27_fu_802_p2[0:0] === 1'b1) ? trunc_ln1494_27_fu_798_p1 : 11'd0);

assign select_ln81_28_fu_826_p3 = ((icmp_ln1494_28_fu_820_p2[0:0] === 1'b1) ? trunc_ln1494_28_fu_816_p1 : 11'd0);

assign select_ln81_29_fu_844_p3 = ((icmp_ln1494_29_fu_838_p2[0:0] === 1'b1) ? trunc_ln1494_29_fu_834_p1 : 11'd0);

assign select_ln81_2_fu_358_p3 = ((icmp_ln1494_2_fu_352_p2[0:0] === 1'b1) ? trunc_ln1494_2_fu_348_p1 : 11'd0);

assign select_ln81_30_fu_862_p3 = ((icmp_ln1494_30_fu_856_p2[0:0] === 1'b1) ? trunc_ln1494_30_fu_852_p1 : 11'd0);

assign select_ln81_31_fu_880_p3 = ((icmp_ln1494_31_fu_874_p2[0:0] === 1'b1) ? trunc_ln1494_31_fu_870_p1 : 11'd0);

assign select_ln81_32_fu_898_p3 = ((icmp_ln1494_32_fu_892_p2[0:0] === 1'b1) ? trunc_ln1494_32_fu_888_p1 : 11'd0);

assign select_ln81_33_fu_916_p3 = ((icmp_ln1494_33_fu_910_p2[0:0] === 1'b1) ? trunc_ln1494_33_fu_906_p1 : 11'd0);

assign select_ln81_34_fu_934_p3 = ((icmp_ln1494_34_fu_928_p2[0:0] === 1'b1) ? trunc_ln1494_34_fu_924_p1 : 11'd0);

assign select_ln81_35_fu_952_p3 = ((icmp_ln1494_35_fu_946_p2[0:0] === 1'b1) ? trunc_ln1494_35_fu_942_p1 : 11'd0);

assign select_ln81_3_fu_376_p3 = ((icmp_ln1494_3_fu_370_p2[0:0] === 1'b1) ? trunc_ln1494_3_fu_366_p1 : 11'd0);

assign select_ln81_4_fu_394_p3 = ((icmp_ln1494_4_fu_388_p2[0:0] === 1'b1) ? trunc_ln1494_4_fu_384_p1 : 11'd0);

assign select_ln81_5_fu_412_p3 = ((icmp_ln1494_5_fu_406_p2[0:0] === 1'b1) ? trunc_ln1494_5_fu_402_p1 : 11'd0);

assign select_ln81_6_fu_430_p3 = ((icmp_ln1494_6_fu_424_p2[0:0] === 1'b1) ? trunc_ln1494_6_fu_420_p1 : 11'd0);

assign select_ln81_7_fu_448_p3 = ((icmp_ln1494_7_fu_442_p2[0:0] === 1'b1) ? trunc_ln1494_7_fu_438_p1 : 11'd0);

assign select_ln81_8_fu_466_p3 = ((icmp_ln1494_8_fu_460_p2[0:0] === 1'b1) ? trunc_ln1494_8_fu_456_p1 : 11'd0);

assign select_ln81_9_fu_484_p3 = ((icmp_ln1494_9_fu_478_p2[0:0] === 1'b1) ? trunc_ln1494_9_fu_474_p1 : 11'd0);

assign select_ln81_fu_322_p3 = ((icmp_ln1494_fu_316_p2[0:0] === 1'b1) ? trunc_ln1494_fu_312_p1 : 11'd0);

assign trunc_ln1494_10_fu_492_p1 = data_10_V_read[10:0];

assign trunc_ln1494_11_fu_510_p1 = data_11_V_read[10:0];

assign trunc_ln1494_12_fu_528_p1 = data_12_V_read[10:0];

assign trunc_ln1494_13_fu_546_p1 = data_13_V_read[10:0];

assign trunc_ln1494_14_fu_564_p1 = data_14_V_read[10:0];

assign trunc_ln1494_15_fu_582_p1 = data_15_V_read[10:0];

assign trunc_ln1494_16_fu_600_p1 = data_16_V_read[10:0];

assign trunc_ln1494_17_fu_618_p1 = data_17_V_read[10:0];

assign trunc_ln1494_18_fu_636_p1 = data_18_V_read[10:0];

assign trunc_ln1494_19_fu_654_p1 = data_19_V_read[10:0];

assign trunc_ln1494_1_fu_330_p1 = data_1_V_read[10:0];

assign trunc_ln1494_20_fu_672_p1 = data_20_V_read[10:0];

assign trunc_ln1494_21_fu_690_p1 = data_21_V_read[10:0];

assign trunc_ln1494_22_fu_708_p1 = data_22_V_read[10:0];

assign trunc_ln1494_23_fu_726_p1 = data_23_V_read[10:0];

assign trunc_ln1494_24_fu_744_p1 = data_24_V_read[10:0];

assign trunc_ln1494_25_fu_762_p1 = data_25_V_read[10:0];

assign trunc_ln1494_26_fu_780_p1 = data_26_V_read[10:0];

assign trunc_ln1494_27_fu_798_p1 = data_27_V_read[10:0];

assign trunc_ln1494_28_fu_816_p1 = data_28_V_read[10:0];

assign trunc_ln1494_29_fu_834_p1 = data_29_V_read[10:0];

assign trunc_ln1494_2_fu_348_p1 = data_2_V_read[10:0];

assign trunc_ln1494_30_fu_852_p1 = data_30_V_read[10:0];

assign trunc_ln1494_31_fu_870_p1 = data_31_V_read[10:0];

assign trunc_ln1494_32_fu_888_p1 = data_32_V_read[10:0];

assign trunc_ln1494_33_fu_906_p1 = data_33_V_read[10:0];

assign trunc_ln1494_34_fu_924_p1 = data_34_V_read[10:0];

assign trunc_ln1494_35_fu_942_p1 = data_35_V_read[10:0];

assign trunc_ln1494_3_fu_366_p1 = data_3_V_read[10:0];

assign trunc_ln1494_4_fu_384_p1 = data_4_V_read[10:0];

assign trunc_ln1494_5_fu_402_p1 = data_5_V_read[10:0];

assign trunc_ln1494_6_fu_420_p1 = data_6_V_read[10:0];

assign trunc_ln1494_7_fu_438_p1 = data_7_V_read[10:0];

assign trunc_ln1494_8_fu_456_p1 = data_8_V_read[10:0];

assign trunc_ln1494_9_fu_474_p1 = data_9_V_read[10:0];

assign trunc_ln1494_fu_312_p1 = data_0_V_read[10:0];

endmodule //relu
