// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module product (
        ap_ready,
        a_V,
        w_V,
        ap_return
);


output   ap_ready;
input  [11:0] a_V;
input  [11:0] w_V;
output  [11:0] ap_return;

wire  signed [15:0] r_V_fu_41_p2;

window_mul_mul_12bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 16 ))
window_mul_mul_12bkb_U7(
    .din0(w_V),
    .din1(a_V),
    .dout(r_V_fu_41_p2)
);

assign ap_ready = 1'b1;

assign ap_return = {{r_V_fu_41_p2[15:4]}};

endmodule //product
