// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _product_HH_
#define _product_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "window_mul_mul_12bkb.h"

namespace ap_rtl {

struct product : public sc_module {
    // Port declarations 4
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > a_V;
    sc_in< sc_lv<12> > w_V;
    sc_out< sc_lv<12> > ap_return;


    // Module declarations
    product(sc_module_name name);
    SC_HAS_PROCESS(product);

    ~product();

    sc_trace_file* mVcdFile;

    window_mul_mul_12bkb<1,1,12,12,16>* window_mul_mul_12bkb_U7;
    sc_signal< sc_lv<16> > r_V_fu_41_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
};

}

using namespace ap_rtl;

#endif
