// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "get3DImageIndex.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic get3DImageIndex::ap_const_logic_1 = sc_dt::Log_1;
const bool get3DImageIndex::ap_const_boolean_1 = true;
const sc_lv<12> get3DImageIndex::ap_const_lv12_0 = "000000000000";
const sc_lv<10> get3DImageIndex::ap_const_lv10_0 = "0000000000";
const sc_lv<9> get3DImageIndex::ap_const_lv9_0 = "000000000";
const sc_lv<11> get3DImageIndex::ap_const_lv11_7 = "111";
const sc_lv<16> get3DImageIndex::ap_const_lv16_F27F = "1111001001111111";
const sc_logic get3DImageIndex::ap_const_logic_0 = sc_dt::Log_0;

get3DImageIndex::get3DImageIndex(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_add_ln15_1_fu_116_p2);
    sensitive << ( sext_ln15_fu_106_p1 );
    sensitive << ( add_ln15_fu_110_p2 );

    SC_METHOD(thread_add_ln15_fu_110_p2);
    sensitive << ( sub_ln15_fu_72_p2 );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( add_ln15_1_fu_116_p2 );
    sensitive << ( zext_ln15_3_fu_122_p1 );

    SC_METHOD(thread_sext_ln15_fu_106_p1);
    sensitive << ( sub_ln15_1_fu_100_p2 );

    SC_METHOD(thread_shl_ln15_1_fu_60_p3);
    sensitive << ( trunc_ln15_fu_44_p1 );

    SC_METHOD(thread_shl_ln15_2_fu_82_p3);
    sensitive << ( trunc_ln15_1_fu_78_p1 );

    SC_METHOD(thread_shl_ln15_fu_90_p2);
    sensitive << ( roll );

    SC_METHOD(thread_shl_ln_fu_48_p3);
    sensitive << ( trunc_ln15_fu_44_p1 );

    SC_METHOD(thread_sub_ln15_1_fu_100_p2);
    sensitive << ( shl_ln15_2_fu_82_p3 );
    sensitive << ( zext_ln15_2_fu_96_p1 );

    SC_METHOD(thread_sub_ln15_fu_72_p2);
    sensitive << ( zext_ln15_fu_56_p1 );
    sensitive << ( zext_ln15_1_fu_68_p1 );

    SC_METHOD(thread_trunc_ln15_1_fu_78_p1);
    sensitive << ( roll );

    SC_METHOD(thread_trunc_ln15_fu_44_p1);
    sensitive << ( layer );

    SC_METHOD(thread_zext_ln15_1_fu_68_p1);
    sensitive << ( shl_ln15_1_fu_60_p3 );

    SC_METHOD(thread_zext_ln15_2_fu_96_p1);
    sensitive << ( shl_ln15_fu_90_p2 );

    SC_METHOD(thread_zext_ln15_3_fu_122_p1);
    sensitive << ( strip );

    SC_METHOD(thread_zext_ln15_fu_56_p1);
    sensitive << ( shl_ln_fu_48_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "get3DImageIndex_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, layer, "(port)layer");
    sc_trace(mVcdFile, roll, "(port)roll");
    sc_trace(mVcdFile, strip, "(port)strip");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, trunc_ln15_fu_44_p1, "trunc_ln15_fu_44_p1");
    sc_trace(mVcdFile, shl_ln_fu_48_p3, "shl_ln_fu_48_p3");
    sc_trace(mVcdFile, shl_ln15_1_fu_60_p3, "shl_ln15_1_fu_60_p3");
    sc_trace(mVcdFile, zext_ln15_fu_56_p1, "zext_ln15_fu_56_p1");
    sc_trace(mVcdFile, zext_ln15_1_fu_68_p1, "zext_ln15_1_fu_68_p1");
    sc_trace(mVcdFile, trunc_ln15_1_fu_78_p1, "trunc_ln15_1_fu_78_p1");
    sc_trace(mVcdFile, shl_ln15_fu_90_p2, "shl_ln15_fu_90_p2");
    sc_trace(mVcdFile, shl_ln15_2_fu_82_p3, "shl_ln15_2_fu_82_p3");
    sc_trace(mVcdFile, zext_ln15_2_fu_96_p1, "zext_ln15_2_fu_96_p1");
    sc_trace(mVcdFile, sub_ln15_1_fu_100_p2, "sub_ln15_1_fu_100_p2");
    sc_trace(mVcdFile, sub_ln15_fu_72_p2, "sub_ln15_fu_72_p2");
    sc_trace(mVcdFile, sext_ln15_fu_106_p1, "sext_ln15_fu_106_p1");
    sc_trace(mVcdFile, add_ln15_fu_110_p2, "add_ln15_fu_110_p2");
    sc_trace(mVcdFile, add_ln15_1_fu_116_p2, "add_ln15_1_fu_116_p2");
    sc_trace(mVcdFile, zext_ln15_3_fu_122_p1, "zext_ln15_3_fu_122_p1");
#endif

    }
}

get3DImageIndex::~get3DImageIndex() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void get3DImageIndex::thread_add_ln15_1_fu_116_p2() {
    add_ln15_1_fu_116_p2 = (!sext_ln15_fu_106_p1.read().is_01() || !add_ln15_fu_110_p2.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln15_fu_106_p1.read()) + sc_biguint<16>(add_ln15_fu_110_p2.read()));
}

void get3DImageIndex::thread_add_ln15_fu_110_p2() {
    add_ln15_fu_110_p2 = (!ap_const_lv16_F27F.is_01() || !sub_ln15_fu_72_p2.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_F27F) + sc_biguint<16>(sub_ln15_fu_72_p2.read()));
}

void get3DImageIndex::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void get3DImageIndex::thread_ap_return() {
    ap_return = (!add_ln15_1_fu_116_p2.read().is_01() || !zext_ln15_3_fu_122_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln15_1_fu_116_p2.read()) + sc_biguint<16>(zext_ln15_3_fu_122_p1.read()));
}

void get3DImageIndex::thread_sext_ln15_fu_106_p1() {
    sext_ln15_fu_106_p1 = esl_sext<16,13>(sub_ln15_1_fu_100_p2.read());
}

void get3DImageIndex::thread_shl_ln15_1_fu_60_p3() {
    shl_ln15_1_fu_60_p3 = esl_concat<3,10>(trunc_ln15_fu_44_p1.read(), ap_const_lv10_0);
}

void get3DImageIndex::thread_shl_ln15_2_fu_82_p3() {
    shl_ln15_2_fu_82_p3 = esl_concat<4,9>(trunc_ln15_1_fu_78_p1.read(), ap_const_lv9_0);
}

void get3DImageIndex::thread_shl_ln15_fu_90_p2() {
    shl_ln15_fu_90_p2 = (!ap_const_lv11_7.is_01())? sc_lv<11>(): roll.read() << (unsigned short)ap_const_lv11_7.to_uint();
}

void get3DImageIndex::thread_shl_ln_fu_48_p3() {
    shl_ln_fu_48_p3 = esl_concat<3,12>(trunc_ln15_fu_44_p1.read(), ap_const_lv12_0);
}

void get3DImageIndex::thread_sub_ln15_1_fu_100_p2() {
    sub_ln15_1_fu_100_p2 = (!shl_ln15_2_fu_82_p3.read().is_01() || !zext_ln15_2_fu_96_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(shl_ln15_2_fu_82_p3.read()) - sc_biguint<13>(zext_ln15_2_fu_96_p1.read()));
}

void get3DImageIndex::thread_sub_ln15_fu_72_p2() {
    sub_ln15_fu_72_p2 = (!zext_ln15_fu_56_p1.read().is_01() || !zext_ln15_1_fu_68_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(zext_ln15_fu_56_p1.read()) - sc_biguint<16>(zext_ln15_1_fu_68_p1.read()));
}

void get3DImageIndex::thread_trunc_ln15_1_fu_78_p1() {
    trunc_ln15_1_fu_78_p1 = roll.read().range(4-1, 0);
}

void get3DImageIndex::thread_trunc_ln15_fu_44_p1() {
    trunc_ln15_fu_44_p1 = layer.read().range(3-1, 0);
}

void get3DImageIndex::thread_zext_ln15_1_fu_68_p1() {
    zext_ln15_1_fu_68_p1 = esl_zext<16,13>(shl_ln15_1_fu_60_p3.read());
}

void get3DImageIndex::thread_zext_ln15_2_fu_96_p1() {
    zext_ln15_2_fu_96_p1 = esl_zext<13,11>(shl_ln15_fu_90_p2.read());
}

void get3DImageIndex::thread_zext_ln15_3_fu_122_p1() {
    zext_ln15_3_fu_122_p1 = esl_zext<16,11>(strip.read());
}

void get3DImageIndex::thread_zext_ln15_fu_56_p1() {
    zext_ln15_fu_56_p1 = esl_zext<16,15>(shl_ln_fu_48_p3.read());
}

}

