// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic relu::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> relu::ap_ST_fsm_state1 = "1";
const sc_lv<32> relu::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<12> relu::ap_const_lv12_0 = "000000000000";
const sc_lv<11> relu::ap_const_lv11_0 = "00000000000";
const bool relu::ap_const_boolean_1 = true;

relu::relu(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_fu_322_p3 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_1_fu_340_p3 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_10_fu_502_p3 );
    sensitive << ( ap_return_10_preg );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_11_fu_520_p3 );
    sensitive << ( ap_return_11_preg );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_12_fu_538_p3 );
    sensitive << ( ap_return_12_preg );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_13_fu_556_p3 );
    sensitive << ( ap_return_13_preg );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_14_fu_574_p3 );
    sensitive << ( ap_return_14_preg );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_15_fu_592_p3 );
    sensitive << ( ap_return_15_preg );

    SC_METHOD(thread_ap_return_16);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_16_fu_610_p3 );
    sensitive << ( ap_return_16_preg );

    SC_METHOD(thread_ap_return_17);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_17_fu_628_p3 );
    sensitive << ( ap_return_17_preg );

    SC_METHOD(thread_ap_return_18);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_18_fu_646_p3 );
    sensitive << ( ap_return_18_preg );

    SC_METHOD(thread_ap_return_19);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_19_fu_664_p3 );
    sensitive << ( ap_return_19_preg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_2_fu_358_p3 );
    sensitive << ( ap_return_2_preg );

    SC_METHOD(thread_ap_return_20);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_20_fu_682_p3 );
    sensitive << ( ap_return_20_preg );

    SC_METHOD(thread_ap_return_21);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_21_fu_700_p3 );
    sensitive << ( ap_return_21_preg );

    SC_METHOD(thread_ap_return_22);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_22_fu_718_p3 );
    sensitive << ( ap_return_22_preg );

    SC_METHOD(thread_ap_return_23);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_23_fu_736_p3 );
    sensitive << ( ap_return_23_preg );

    SC_METHOD(thread_ap_return_24);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_24_fu_754_p3 );
    sensitive << ( ap_return_24_preg );

    SC_METHOD(thread_ap_return_25);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_25_fu_772_p3 );
    sensitive << ( ap_return_25_preg );

    SC_METHOD(thread_ap_return_26);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_26_fu_790_p3 );
    sensitive << ( ap_return_26_preg );

    SC_METHOD(thread_ap_return_27);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_27_fu_808_p3 );
    sensitive << ( ap_return_27_preg );

    SC_METHOD(thread_ap_return_28);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_28_fu_826_p3 );
    sensitive << ( ap_return_28_preg );

    SC_METHOD(thread_ap_return_29);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_29_fu_844_p3 );
    sensitive << ( ap_return_29_preg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_3_fu_376_p3 );
    sensitive << ( ap_return_3_preg );

    SC_METHOD(thread_ap_return_30);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_30_fu_862_p3 );
    sensitive << ( ap_return_30_preg );

    SC_METHOD(thread_ap_return_31);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_31_fu_880_p3 );
    sensitive << ( ap_return_31_preg );

    SC_METHOD(thread_ap_return_32);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_32_fu_898_p3 );
    sensitive << ( ap_return_32_preg );

    SC_METHOD(thread_ap_return_33);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_33_fu_916_p3 );
    sensitive << ( ap_return_33_preg );

    SC_METHOD(thread_ap_return_34);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_34_fu_934_p3 );
    sensitive << ( ap_return_34_preg );

    SC_METHOD(thread_ap_return_35);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_35_fu_952_p3 );
    sensitive << ( ap_return_35_preg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_4_fu_394_p3 );
    sensitive << ( ap_return_4_preg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_5_fu_412_p3 );
    sensitive << ( ap_return_5_preg );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_6_fu_430_p3 );
    sensitive << ( ap_return_6_preg );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_7_fu_448_p3 );
    sensitive << ( ap_return_7_preg );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_8_fu_466_p3 );
    sensitive << ( ap_return_8_preg );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( select_ln81_9_fu_484_p3 );
    sensitive << ( ap_return_9_preg );

    SC_METHOD(thread_icmp_ln1494_10_fu_496_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_icmp_ln1494_11_fu_514_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_icmp_ln1494_12_fu_532_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_icmp_ln1494_13_fu_550_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_icmp_ln1494_14_fu_568_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_icmp_ln1494_15_fu_586_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_icmp_ln1494_16_fu_604_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_icmp_ln1494_17_fu_622_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_icmp_ln1494_18_fu_640_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_icmp_ln1494_19_fu_658_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_icmp_ln1494_1_fu_334_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_icmp_ln1494_20_fu_676_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_icmp_ln1494_21_fu_694_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_icmp_ln1494_22_fu_712_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_icmp_ln1494_23_fu_730_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_icmp_ln1494_24_fu_748_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_icmp_ln1494_25_fu_766_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_icmp_ln1494_26_fu_784_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_icmp_ln1494_27_fu_802_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_icmp_ln1494_28_fu_820_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_icmp_ln1494_29_fu_838_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_icmp_ln1494_2_fu_352_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_icmp_ln1494_30_fu_856_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_icmp_ln1494_31_fu_874_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_icmp_ln1494_32_fu_892_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_32_V_read );

    SC_METHOD(thread_icmp_ln1494_33_fu_910_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_33_V_read );

    SC_METHOD(thread_icmp_ln1494_34_fu_928_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_34_V_read );

    SC_METHOD(thread_icmp_ln1494_35_fu_946_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_35_V_read );

    SC_METHOD(thread_icmp_ln1494_3_fu_370_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_icmp_ln1494_4_fu_388_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_icmp_ln1494_5_fu_406_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_icmp_ln1494_6_fu_424_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_icmp_ln1494_7_fu_442_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_icmp_ln1494_8_fu_460_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_icmp_ln1494_9_fu_478_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_icmp_ln1494_fu_316_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_select_ln81_10_fu_502_p3);
    sensitive << ( icmp_ln1494_10_fu_496_p2 );
    sensitive << ( trunc_ln1494_10_fu_492_p1 );

    SC_METHOD(thread_select_ln81_11_fu_520_p3);
    sensitive << ( icmp_ln1494_11_fu_514_p2 );
    sensitive << ( trunc_ln1494_11_fu_510_p1 );

    SC_METHOD(thread_select_ln81_12_fu_538_p3);
    sensitive << ( icmp_ln1494_12_fu_532_p2 );
    sensitive << ( trunc_ln1494_12_fu_528_p1 );

    SC_METHOD(thread_select_ln81_13_fu_556_p3);
    sensitive << ( icmp_ln1494_13_fu_550_p2 );
    sensitive << ( trunc_ln1494_13_fu_546_p1 );

    SC_METHOD(thread_select_ln81_14_fu_574_p3);
    sensitive << ( icmp_ln1494_14_fu_568_p2 );
    sensitive << ( trunc_ln1494_14_fu_564_p1 );

    SC_METHOD(thread_select_ln81_15_fu_592_p3);
    sensitive << ( icmp_ln1494_15_fu_586_p2 );
    sensitive << ( trunc_ln1494_15_fu_582_p1 );

    SC_METHOD(thread_select_ln81_16_fu_610_p3);
    sensitive << ( icmp_ln1494_16_fu_604_p2 );
    sensitive << ( trunc_ln1494_16_fu_600_p1 );

    SC_METHOD(thread_select_ln81_17_fu_628_p3);
    sensitive << ( icmp_ln1494_17_fu_622_p2 );
    sensitive << ( trunc_ln1494_17_fu_618_p1 );

    SC_METHOD(thread_select_ln81_18_fu_646_p3);
    sensitive << ( icmp_ln1494_18_fu_640_p2 );
    sensitive << ( trunc_ln1494_18_fu_636_p1 );

    SC_METHOD(thread_select_ln81_19_fu_664_p3);
    sensitive << ( icmp_ln1494_19_fu_658_p2 );
    sensitive << ( trunc_ln1494_19_fu_654_p1 );

    SC_METHOD(thread_select_ln81_1_fu_340_p3);
    sensitive << ( icmp_ln1494_1_fu_334_p2 );
    sensitive << ( trunc_ln1494_1_fu_330_p1 );

    SC_METHOD(thread_select_ln81_20_fu_682_p3);
    sensitive << ( icmp_ln1494_20_fu_676_p2 );
    sensitive << ( trunc_ln1494_20_fu_672_p1 );

    SC_METHOD(thread_select_ln81_21_fu_700_p3);
    sensitive << ( icmp_ln1494_21_fu_694_p2 );
    sensitive << ( trunc_ln1494_21_fu_690_p1 );

    SC_METHOD(thread_select_ln81_22_fu_718_p3);
    sensitive << ( icmp_ln1494_22_fu_712_p2 );
    sensitive << ( trunc_ln1494_22_fu_708_p1 );

    SC_METHOD(thread_select_ln81_23_fu_736_p3);
    sensitive << ( icmp_ln1494_23_fu_730_p2 );
    sensitive << ( trunc_ln1494_23_fu_726_p1 );

    SC_METHOD(thread_select_ln81_24_fu_754_p3);
    sensitive << ( icmp_ln1494_24_fu_748_p2 );
    sensitive << ( trunc_ln1494_24_fu_744_p1 );

    SC_METHOD(thread_select_ln81_25_fu_772_p3);
    sensitive << ( icmp_ln1494_25_fu_766_p2 );
    sensitive << ( trunc_ln1494_25_fu_762_p1 );

    SC_METHOD(thread_select_ln81_26_fu_790_p3);
    sensitive << ( icmp_ln1494_26_fu_784_p2 );
    sensitive << ( trunc_ln1494_26_fu_780_p1 );

    SC_METHOD(thread_select_ln81_27_fu_808_p3);
    sensitive << ( icmp_ln1494_27_fu_802_p2 );
    sensitive << ( trunc_ln1494_27_fu_798_p1 );

    SC_METHOD(thread_select_ln81_28_fu_826_p3);
    sensitive << ( icmp_ln1494_28_fu_820_p2 );
    sensitive << ( trunc_ln1494_28_fu_816_p1 );

    SC_METHOD(thread_select_ln81_29_fu_844_p3);
    sensitive << ( icmp_ln1494_29_fu_838_p2 );
    sensitive << ( trunc_ln1494_29_fu_834_p1 );

    SC_METHOD(thread_select_ln81_2_fu_358_p3);
    sensitive << ( icmp_ln1494_2_fu_352_p2 );
    sensitive << ( trunc_ln1494_2_fu_348_p1 );

    SC_METHOD(thread_select_ln81_30_fu_862_p3);
    sensitive << ( icmp_ln1494_30_fu_856_p2 );
    sensitive << ( trunc_ln1494_30_fu_852_p1 );

    SC_METHOD(thread_select_ln81_31_fu_880_p3);
    sensitive << ( icmp_ln1494_31_fu_874_p2 );
    sensitive << ( trunc_ln1494_31_fu_870_p1 );

    SC_METHOD(thread_select_ln81_32_fu_898_p3);
    sensitive << ( icmp_ln1494_32_fu_892_p2 );
    sensitive << ( trunc_ln1494_32_fu_888_p1 );

    SC_METHOD(thread_select_ln81_33_fu_916_p3);
    sensitive << ( icmp_ln1494_33_fu_910_p2 );
    sensitive << ( trunc_ln1494_33_fu_906_p1 );

    SC_METHOD(thread_select_ln81_34_fu_934_p3);
    sensitive << ( icmp_ln1494_34_fu_928_p2 );
    sensitive << ( trunc_ln1494_34_fu_924_p1 );

    SC_METHOD(thread_select_ln81_35_fu_952_p3);
    sensitive << ( icmp_ln1494_35_fu_946_p2 );
    sensitive << ( trunc_ln1494_35_fu_942_p1 );

    SC_METHOD(thread_select_ln81_3_fu_376_p3);
    sensitive << ( icmp_ln1494_3_fu_370_p2 );
    sensitive << ( trunc_ln1494_3_fu_366_p1 );

    SC_METHOD(thread_select_ln81_4_fu_394_p3);
    sensitive << ( icmp_ln1494_4_fu_388_p2 );
    sensitive << ( trunc_ln1494_4_fu_384_p1 );

    SC_METHOD(thread_select_ln81_5_fu_412_p3);
    sensitive << ( icmp_ln1494_5_fu_406_p2 );
    sensitive << ( trunc_ln1494_5_fu_402_p1 );

    SC_METHOD(thread_select_ln81_6_fu_430_p3);
    sensitive << ( icmp_ln1494_6_fu_424_p2 );
    sensitive << ( trunc_ln1494_6_fu_420_p1 );

    SC_METHOD(thread_select_ln81_7_fu_448_p3);
    sensitive << ( icmp_ln1494_7_fu_442_p2 );
    sensitive << ( trunc_ln1494_7_fu_438_p1 );

    SC_METHOD(thread_select_ln81_8_fu_466_p3);
    sensitive << ( icmp_ln1494_8_fu_460_p2 );
    sensitive << ( trunc_ln1494_8_fu_456_p1 );

    SC_METHOD(thread_select_ln81_9_fu_484_p3);
    sensitive << ( icmp_ln1494_9_fu_478_p2 );
    sensitive << ( trunc_ln1494_9_fu_474_p1 );

    SC_METHOD(thread_select_ln81_fu_322_p3);
    sensitive << ( icmp_ln1494_fu_316_p2 );
    sensitive << ( trunc_ln1494_fu_312_p1 );

    SC_METHOD(thread_trunc_ln1494_10_fu_492_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_trunc_ln1494_11_fu_510_p1);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_trunc_ln1494_12_fu_528_p1);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_trunc_ln1494_13_fu_546_p1);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_trunc_ln1494_14_fu_564_p1);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_trunc_ln1494_15_fu_582_p1);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_trunc_ln1494_16_fu_600_p1);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_trunc_ln1494_17_fu_618_p1);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_trunc_ln1494_18_fu_636_p1);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_trunc_ln1494_19_fu_654_p1);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_trunc_ln1494_1_fu_330_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_trunc_ln1494_20_fu_672_p1);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_trunc_ln1494_21_fu_690_p1);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_trunc_ln1494_22_fu_708_p1);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_trunc_ln1494_23_fu_726_p1);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_trunc_ln1494_24_fu_744_p1);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_trunc_ln1494_25_fu_762_p1);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_trunc_ln1494_26_fu_780_p1);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_trunc_ln1494_27_fu_798_p1);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_trunc_ln1494_28_fu_816_p1);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_trunc_ln1494_29_fu_834_p1);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_trunc_ln1494_2_fu_348_p1);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_trunc_ln1494_30_fu_852_p1);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_trunc_ln1494_31_fu_870_p1);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_trunc_ln1494_32_fu_888_p1);
    sensitive << ( data_32_V_read );

    SC_METHOD(thread_trunc_ln1494_33_fu_906_p1);
    sensitive << ( data_33_V_read );

    SC_METHOD(thread_trunc_ln1494_34_fu_924_p1);
    sensitive << ( data_34_V_read );

    SC_METHOD(thread_trunc_ln1494_35_fu_942_p1);
    sensitive << ( data_35_V_read );

    SC_METHOD(thread_trunc_ln1494_3_fu_366_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_trunc_ln1494_4_fu_384_p1);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_trunc_ln1494_5_fu_402_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_trunc_ln1494_6_fu_420_p1);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_trunc_ln1494_7_fu_438_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_trunc_ln1494_8_fu_456_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_trunc_ln1494_9_fu_474_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_trunc_ln1494_fu_312_p1);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    ap_return_0_preg = "00000000000";
    ap_return_1_preg = "00000000000";
    ap_return_2_preg = "00000000000";
    ap_return_3_preg = "00000000000";
    ap_return_4_preg = "00000000000";
    ap_return_5_preg = "00000000000";
    ap_return_6_preg = "00000000000";
    ap_return_7_preg = "00000000000";
    ap_return_8_preg = "00000000000";
    ap_return_9_preg = "00000000000";
    ap_return_10_preg = "00000000000";
    ap_return_11_preg = "00000000000";
    ap_return_12_preg = "00000000000";
    ap_return_13_preg = "00000000000";
    ap_return_14_preg = "00000000000";
    ap_return_15_preg = "00000000000";
    ap_return_16_preg = "00000000000";
    ap_return_17_preg = "00000000000";
    ap_return_18_preg = "00000000000";
    ap_return_19_preg = "00000000000";
    ap_return_20_preg = "00000000000";
    ap_return_21_preg = "00000000000";
    ap_return_22_preg = "00000000000";
    ap_return_23_preg = "00000000000";
    ap_return_24_preg = "00000000000";
    ap_return_25_preg = "00000000000";
    ap_return_26_preg = "00000000000";
    ap_return_27_preg = "00000000000";
    ap_return_28_preg = "00000000000";
    ap_return_29_preg = "00000000000";
    ap_return_30_preg = "00000000000";
    ap_return_31_preg = "00000000000";
    ap_return_32_preg = "00000000000";
    ap_return_33_preg = "00000000000";
    ap_return_34_preg = "00000000000";
    ap_return_35_preg = "00000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, data_20_V_read, "(port)data_20_V_read");
    sc_trace(mVcdFile, data_21_V_read, "(port)data_21_V_read");
    sc_trace(mVcdFile, data_22_V_read, "(port)data_22_V_read");
    sc_trace(mVcdFile, data_23_V_read, "(port)data_23_V_read");
    sc_trace(mVcdFile, data_24_V_read, "(port)data_24_V_read");
    sc_trace(mVcdFile, data_25_V_read, "(port)data_25_V_read");
    sc_trace(mVcdFile, data_26_V_read, "(port)data_26_V_read");
    sc_trace(mVcdFile, data_27_V_read, "(port)data_27_V_read");
    sc_trace(mVcdFile, data_28_V_read, "(port)data_28_V_read");
    sc_trace(mVcdFile, data_29_V_read, "(port)data_29_V_read");
    sc_trace(mVcdFile, data_30_V_read, "(port)data_30_V_read");
    sc_trace(mVcdFile, data_31_V_read, "(port)data_31_V_read");
    sc_trace(mVcdFile, data_32_V_read, "(port)data_32_V_read");
    sc_trace(mVcdFile, data_33_V_read, "(port)data_33_V_read");
    sc_trace(mVcdFile, data_34_V_read, "(port)data_34_V_read");
    sc_trace(mVcdFile, data_35_V_read, "(port)data_35_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
    sc_trace(mVcdFile, ap_return_16, "(port)ap_return_16");
    sc_trace(mVcdFile, ap_return_17, "(port)ap_return_17");
    sc_trace(mVcdFile, ap_return_18, "(port)ap_return_18");
    sc_trace(mVcdFile, ap_return_19, "(port)ap_return_19");
    sc_trace(mVcdFile, ap_return_20, "(port)ap_return_20");
    sc_trace(mVcdFile, ap_return_21, "(port)ap_return_21");
    sc_trace(mVcdFile, ap_return_22, "(port)ap_return_22");
    sc_trace(mVcdFile, ap_return_23, "(port)ap_return_23");
    sc_trace(mVcdFile, ap_return_24, "(port)ap_return_24");
    sc_trace(mVcdFile, ap_return_25, "(port)ap_return_25");
    sc_trace(mVcdFile, ap_return_26, "(port)ap_return_26");
    sc_trace(mVcdFile, ap_return_27, "(port)ap_return_27");
    sc_trace(mVcdFile, ap_return_28, "(port)ap_return_28");
    sc_trace(mVcdFile, ap_return_29, "(port)ap_return_29");
    sc_trace(mVcdFile, ap_return_30, "(port)ap_return_30");
    sc_trace(mVcdFile, ap_return_31, "(port)ap_return_31");
    sc_trace(mVcdFile, ap_return_32, "(port)ap_return_32");
    sc_trace(mVcdFile, ap_return_33, "(port)ap_return_33");
    sc_trace(mVcdFile, ap_return_34, "(port)ap_return_34");
    sc_trace(mVcdFile, ap_return_35, "(port)ap_return_35");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, icmp_ln1494_fu_316_p2, "icmp_ln1494_fu_316_p2");
    sc_trace(mVcdFile, trunc_ln1494_fu_312_p1, "trunc_ln1494_fu_312_p1");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_334_p2, "icmp_ln1494_1_fu_334_p2");
    sc_trace(mVcdFile, trunc_ln1494_1_fu_330_p1, "trunc_ln1494_1_fu_330_p1");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_352_p2, "icmp_ln1494_2_fu_352_p2");
    sc_trace(mVcdFile, trunc_ln1494_2_fu_348_p1, "trunc_ln1494_2_fu_348_p1");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_370_p2, "icmp_ln1494_3_fu_370_p2");
    sc_trace(mVcdFile, trunc_ln1494_3_fu_366_p1, "trunc_ln1494_3_fu_366_p1");
    sc_trace(mVcdFile, icmp_ln1494_4_fu_388_p2, "icmp_ln1494_4_fu_388_p2");
    sc_trace(mVcdFile, trunc_ln1494_4_fu_384_p1, "trunc_ln1494_4_fu_384_p1");
    sc_trace(mVcdFile, icmp_ln1494_5_fu_406_p2, "icmp_ln1494_5_fu_406_p2");
    sc_trace(mVcdFile, trunc_ln1494_5_fu_402_p1, "trunc_ln1494_5_fu_402_p1");
    sc_trace(mVcdFile, icmp_ln1494_6_fu_424_p2, "icmp_ln1494_6_fu_424_p2");
    sc_trace(mVcdFile, trunc_ln1494_6_fu_420_p1, "trunc_ln1494_6_fu_420_p1");
    sc_trace(mVcdFile, icmp_ln1494_7_fu_442_p2, "icmp_ln1494_7_fu_442_p2");
    sc_trace(mVcdFile, trunc_ln1494_7_fu_438_p1, "trunc_ln1494_7_fu_438_p1");
    sc_trace(mVcdFile, icmp_ln1494_8_fu_460_p2, "icmp_ln1494_8_fu_460_p2");
    sc_trace(mVcdFile, trunc_ln1494_8_fu_456_p1, "trunc_ln1494_8_fu_456_p1");
    sc_trace(mVcdFile, icmp_ln1494_9_fu_478_p2, "icmp_ln1494_9_fu_478_p2");
    sc_trace(mVcdFile, trunc_ln1494_9_fu_474_p1, "trunc_ln1494_9_fu_474_p1");
    sc_trace(mVcdFile, icmp_ln1494_10_fu_496_p2, "icmp_ln1494_10_fu_496_p2");
    sc_trace(mVcdFile, trunc_ln1494_10_fu_492_p1, "trunc_ln1494_10_fu_492_p1");
    sc_trace(mVcdFile, icmp_ln1494_11_fu_514_p2, "icmp_ln1494_11_fu_514_p2");
    sc_trace(mVcdFile, trunc_ln1494_11_fu_510_p1, "trunc_ln1494_11_fu_510_p1");
    sc_trace(mVcdFile, icmp_ln1494_12_fu_532_p2, "icmp_ln1494_12_fu_532_p2");
    sc_trace(mVcdFile, trunc_ln1494_12_fu_528_p1, "trunc_ln1494_12_fu_528_p1");
    sc_trace(mVcdFile, icmp_ln1494_13_fu_550_p2, "icmp_ln1494_13_fu_550_p2");
    sc_trace(mVcdFile, trunc_ln1494_13_fu_546_p1, "trunc_ln1494_13_fu_546_p1");
    sc_trace(mVcdFile, icmp_ln1494_14_fu_568_p2, "icmp_ln1494_14_fu_568_p2");
    sc_trace(mVcdFile, trunc_ln1494_14_fu_564_p1, "trunc_ln1494_14_fu_564_p1");
    sc_trace(mVcdFile, icmp_ln1494_15_fu_586_p2, "icmp_ln1494_15_fu_586_p2");
    sc_trace(mVcdFile, trunc_ln1494_15_fu_582_p1, "trunc_ln1494_15_fu_582_p1");
    sc_trace(mVcdFile, icmp_ln1494_16_fu_604_p2, "icmp_ln1494_16_fu_604_p2");
    sc_trace(mVcdFile, trunc_ln1494_16_fu_600_p1, "trunc_ln1494_16_fu_600_p1");
    sc_trace(mVcdFile, icmp_ln1494_17_fu_622_p2, "icmp_ln1494_17_fu_622_p2");
    sc_trace(mVcdFile, trunc_ln1494_17_fu_618_p1, "trunc_ln1494_17_fu_618_p1");
    sc_trace(mVcdFile, icmp_ln1494_18_fu_640_p2, "icmp_ln1494_18_fu_640_p2");
    sc_trace(mVcdFile, trunc_ln1494_18_fu_636_p1, "trunc_ln1494_18_fu_636_p1");
    sc_trace(mVcdFile, icmp_ln1494_19_fu_658_p2, "icmp_ln1494_19_fu_658_p2");
    sc_trace(mVcdFile, trunc_ln1494_19_fu_654_p1, "trunc_ln1494_19_fu_654_p1");
    sc_trace(mVcdFile, icmp_ln1494_20_fu_676_p2, "icmp_ln1494_20_fu_676_p2");
    sc_trace(mVcdFile, trunc_ln1494_20_fu_672_p1, "trunc_ln1494_20_fu_672_p1");
    sc_trace(mVcdFile, icmp_ln1494_21_fu_694_p2, "icmp_ln1494_21_fu_694_p2");
    sc_trace(mVcdFile, trunc_ln1494_21_fu_690_p1, "trunc_ln1494_21_fu_690_p1");
    sc_trace(mVcdFile, icmp_ln1494_22_fu_712_p2, "icmp_ln1494_22_fu_712_p2");
    sc_trace(mVcdFile, trunc_ln1494_22_fu_708_p1, "trunc_ln1494_22_fu_708_p1");
    sc_trace(mVcdFile, icmp_ln1494_23_fu_730_p2, "icmp_ln1494_23_fu_730_p2");
    sc_trace(mVcdFile, trunc_ln1494_23_fu_726_p1, "trunc_ln1494_23_fu_726_p1");
    sc_trace(mVcdFile, icmp_ln1494_24_fu_748_p2, "icmp_ln1494_24_fu_748_p2");
    sc_trace(mVcdFile, trunc_ln1494_24_fu_744_p1, "trunc_ln1494_24_fu_744_p1");
    sc_trace(mVcdFile, icmp_ln1494_25_fu_766_p2, "icmp_ln1494_25_fu_766_p2");
    sc_trace(mVcdFile, trunc_ln1494_25_fu_762_p1, "trunc_ln1494_25_fu_762_p1");
    sc_trace(mVcdFile, icmp_ln1494_26_fu_784_p2, "icmp_ln1494_26_fu_784_p2");
    sc_trace(mVcdFile, trunc_ln1494_26_fu_780_p1, "trunc_ln1494_26_fu_780_p1");
    sc_trace(mVcdFile, icmp_ln1494_27_fu_802_p2, "icmp_ln1494_27_fu_802_p2");
    sc_trace(mVcdFile, trunc_ln1494_27_fu_798_p1, "trunc_ln1494_27_fu_798_p1");
    sc_trace(mVcdFile, icmp_ln1494_28_fu_820_p2, "icmp_ln1494_28_fu_820_p2");
    sc_trace(mVcdFile, trunc_ln1494_28_fu_816_p1, "trunc_ln1494_28_fu_816_p1");
    sc_trace(mVcdFile, icmp_ln1494_29_fu_838_p2, "icmp_ln1494_29_fu_838_p2");
    sc_trace(mVcdFile, trunc_ln1494_29_fu_834_p1, "trunc_ln1494_29_fu_834_p1");
    sc_trace(mVcdFile, icmp_ln1494_30_fu_856_p2, "icmp_ln1494_30_fu_856_p2");
    sc_trace(mVcdFile, trunc_ln1494_30_fu_852_p1, "trunc_ln1494_30_fu_852_p1");
    sc_trace(mVcdFile, icmp_ln1494_31_fu_874_p2, "icmp_ln1494_31_fu_874_p2");
    sc_trace(mVcdFile, trunc_ln1494_31_fu_870_p1, "trunc_ln1494_31_fu_870_p1");
    sc_trace(mVcdFile, icmp_ln1494_32_fu_892_p2, "icmp_ln1494_32_fu_892_p2");
    sc_trace(mVcdFile, trunc_ln1494_32_fu_888_p1, "trunc_ln1494_32_fu_888_p1");
    sc_trace(mVcdFile, icmp_ln1494_33_fu_910_p2, "icmp_ln1494_33_fu_910_p2");
    sc_trace(mVcdFile, trunc_ln1494_33_fu_906_p1, "trunc_ln1494_33_fu_906_p1");
    sc_trace(mVcdFile, icmp_ln1494_34_fu_928_p2, "icmp_ln1494_34_fu_928_p2");
    sc_trace(mVcdFile, trunc_ln1494_34_fu_924_p1, "trunc_ln1494_34_fu_924_p1");
    sc_trace(mVcdFile, icmp_ln1494_35_fu_946_p2, "icmp_ln1494_35_fu_946_p2");
    sc_trace(mVcdFile, trunc_ln1494_35_fu_942_p1, "trunc_ln1494_35_fu_942_p1");
    sc_trace(mVcdFile, select_ln81_fu_322_p3, "select_ln81_fu_322_p3");
    sc_trace(mVcdFile, select_ln81_1_fu_340_p3, "select_ln81_1_fu_340_p3");
    sc_trace(mVcdFile, select_ln81_2_fu_358_p3, "select_ln81_2_fu_358_p3");
    sc_trace(mVcdFile, select_ln81_3_fu_376_p3, "select_ln81_3_fu_376_p3");
    sc_trace(mVcdFile, select_ln81_4_fu_394_p3, "select_ln81_4_fu_394_p3");
    sc_trace(mVcdFile, select_ln81_5_fu_412_p3, "select_ln81_5_fu_412_p3");
    sc_trace(mVcdFile, select_ln81_6_fu_430_p3, "select_ln81_6_fu_430_p3");
    sc_trace(mVcdFile, select_ln81_7_fu_448_p3, "select_ln81_7_fu_448_p3");
    sc_trace(mVcdFile, select_ln81_8_fu_466_p3, "select_ln81_8_fu_466_p3");
    sc_trace(mVcdFile, select_ln81_9_fu_484_p3, "select_ln81_9_fu_484_p3");
    sc_trace(mVcdFile, select_ln81_10_fu_502_p3, "select_ln81_10_fu_502_p3");
    sc_trace(mVcdFile, select_ln81_11_fu_520_p3, "select_ln81_11_fu_520_p3");
    sc_trace(mVcdFile, select_ln81_12_fu_538_p3, "select_ln81_12_fu_538_p3");
    sc_trace(mVcdFile, select_ln81_13_fu_556_p3, "select_ln81_13_fu_556_p3");
    sc_trace(mVcdFile, select_ln81_14_fu_574_p3, "select_ln81_14_fu_574_p3");
    sc_trace(mVcdFile, select_ln81_15_fu_592_p3, "select_ln81_15_fu_592_p3");
    sc_trace(mVcdFile, select_ln81_16_fu_610_p3, "select_ln81_16_fu_610_p3");
    sc_trace(mVcdFile, select_ln81_17_fu_628_p3, "select_ln81_17_fu_628_p3");
    sc_trace(mVcdFile, select_ln81_18_fu_646_p3, "select_ln81_18_fu_646_p3");
    sc_trace(mVcdFile, select_ln81_19_fu_664_p3, "select_ln81_19_fu_664_p3");
    sc_trace(mVcdFile, select_ln81_20_fu_682_p3, "select_ln81_20_fu_682_p3");
    sc_trace(mVcdFile, select_ln81_21_fu_700_p3, "select_ln81_21_fu_700_p3");
    sc_trace(mVcdFile, select_ln81_22_fu_718_p3, "select_ln81_22_fu_718_p3");
    sc_trace(mVcdFile, select_ln81_23_fu_736_p3, "select_ln81_23_fu_736_p3");
    sc_trace(mVcdFile, select_ln81_24_fu_754_p3, "select_ln81_24_fu_754_p3");
    sc_trace(mVcdFile, select_ln81_25_fu_772_p3, "select_ln81_25_fu_772_p3");
    sc_trace(mVcdFile, select_ln81_26_fu_790_p3, "select_ln81_26_fu_790_p3");
    sc_trace(mVcdFile, select_ln81_27_fu_808_p3, "select_ln81_27_fu_808_p3");
    sc_trace(mVcdFile, select_ln81_28_fu_826_p3, "select_ln81_28_fu_826_p3");
    sc_trace(mVcdFile, select_ln81_29_fu_844_p3, "select_ln81_29_fu_844_p3");
    sc_trace(mVcdFile, select_ln81_30_fu_862_p3, "select_ln81_30_fu_862_p3");
    sc_trace(mVcdFile, select_ln81_31_fu_880_p3, "select_ln81_31_fu_880_p3");
    sc_trace(mVcdFile, select_ln81_32_fu_898_p3, "select_ln81_32_fu_898_p3");
    sc_trace(mVcdFile, select_ln81_33_fu_916_p3, "select_ln81_33_fu_916_p3");
    sc_trace(mVcdFile, select_ln81_34_fu_934_p3, "select_ln81_34_fu_934_p3");
    sc_trace(mVcdFile, select_ln81_35_fu_952_p3, "select_ln81_35_fu_952_p3");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_return_2_preg, "ap_return_2_preg");
    sc_trace(mVcdFile, ap_return_3_preg, "ap_return_3_preg");
    sc_trace(mVcdFile, ap_return_4_preg, "ap_return_4_preg");
    sc_trace(mVcdFile, ap_return_5_preg, "ap_return_5_preg");
    sc_trace(mVcdFile, ap_return_6_preg, "ap_return_6_preg");
    sc_trace(mVcdFile, ap_return_7_preg, "ap_return_7_preg");
    sc_trace(mVcdFile, ap_return_8_preg, "ap_return_8_preg");
    sc_trace(mVcdFile, ap_return_9_preg, "ap_return_9_preg");
    sc_trace(mVcdFile, ap_return_10_preg, "ap_return_10_preg");
    sc_trace(mVcdFile, ap_return_11_preg, "ap_return_11_preg");
    sc_trace(mVcdFile, ap_return_12_preg, "ap_return_12_preg");
    sc_trace(mVcdFile, ap_return_13_preg, "ap_return_13_preg");
    sc_trace(mVcdFile, ap_return_14_preg, "ap_return_14_preg");
    sc_trace(mVcdFile, ap_return_15_preg, "ap_return_15_preg");
    sc_trace(mVcdFile, ap_return_16_preg, "ap_return_16_preg");
    sc_trace(mVcdFile, ap_return_17_preg, "ap_return_17_preg");
    sc_trace(mVcdFile, ap_return_18_preg, "ap_return_18_preg");
    sc_trace(mVcdFile, ap_return_19_preg, "ap_return_19_preg");
    sc_trace(mVcdFile, ap_return_20_preg, "ap_return_20_preg");
    sc_trace(mVcdFile, ap_return_21_preg, "ap_return_21_preg");
    sc_trace(mVcdFile, ap_return_22_preg, "ap_return_22_preg");
    sc_trace(mVcdFile, ap_return_23_preg, "ap_return_23_preg");
    sc_trace(mVcdFile, ap_return_24_preg, "ap_return_24_preg");
    sc_trace(mVcdFile, ap_return_25_preg, "ap_return_25_preg");
    sc_trace(mVcdFile, ap_return_26_preg, "ap_return_26_preg");
    sc_trace(mVcdFile, ap_return_27_preg, "ap_return_27_preg");
    sc_trace(mVcdFile, ap_return_28_preg, "ap_return_28_preg");
    sc_trace(mVcdFile, ap_return_29_preg, "ap_return_29_preg");
    sc_trace(mVcdFile, ap_return_30_preg, "ap_return_30_preg");
    sc_trace(mVcdFile, ap_return_31_preg, "ap_return_31_preg");
    sc_trace(mVcdFile, ap_return_32_preg, "ap_return_32_preg");
    sc_trace(mVcdFile, ap_return_33_preg, "ap_return_33_preg");
    sc_trace(mVcdFile, ap_return_34_preg, "ap_return_34_preg");
    sc_trace(mVcdFile, ap_return_35_preg, "ap_return_35_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

relu::~relu() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_0_preg = select_ln81_fu_322_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_10_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_10_preg = select_ln81_10_fu_502_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_11_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_11_preg = select_ln81_11_fu_520_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_12_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_12_preg = select_ln81_12_fu_538_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_13_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_13_preg = select_ln81_13_fu_556_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_14_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_14_preg = select_ln81_14_fu_574_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_15_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_15_preg = select_ln81_15_fu_592_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_16_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_16_preg = select_ln81_16_fu_610_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_17_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_17_preg = select_ln81_17_fu_628_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_18_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_18_preg = select_ln81_18_fu_646_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_19_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_19_preg = select_ln81_19_fu_664_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_1_preg = select_ln81_1_fu_340_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_20_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_20_preg = select_ln81_20_fu_682_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_21_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_21_preg = select_ln81_21_fu_700_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_22_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_22_preg = select_ln81_22_fu_718_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_23_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_23_preg = select_ln81_23_fu_736_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_24_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_24_preg = select_ln81_24_fu_754_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_25_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_25_preg = select_ln81_25_fu_772_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_26_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_26_preg = select_ln81_26_fu_790_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_27_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_27_preg = select_ln81_27_fu_808_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_28_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_28_preg = select_ln81_28_fu_826_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_29_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_29_preg = select_ln81_29_fu_844_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_2_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_2_preg = select_ln81_2_fu_358_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_30_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_30_preg = select_ln81_30_fu_862_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_31_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_31_preg = select_ln81_31_fu_880_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_32_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_32_preg = select_ln81_32_fu_898_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_33_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_33_preg = select_ln81_33_fu_916_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_34_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_34_preg = select_ln81_34_fu_934_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_35_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_35_preg = select_ln81_35_fu_952_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_3_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_3_preg = select_ln81_3_fu_376_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_4_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_4_preg = select_ln81_4_fu_394_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_5_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_5_preg = select_ln81_5_fu_412_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_6_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_6_preg = select_ln81_6_fu_430_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_7_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_7_preg = select_ln81_7_fu_448_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_8_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_8_preg = select_ln81_8_fu_466_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_9_preg = ap_const_lv11_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_return_9_preg = select_ln81_9_fu_484_p3.read();
        }
    }
}

void relu::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void relu::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void relu::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void relu::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void relu::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void relu::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_0 = select_ln81_fu_322_p3.read();
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void relu::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_1 = select_ln81_1_fu_340_p3.read();
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void relu::thread_ap_return_10() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_10 = select_ln81_10_fu_502_p3.read();
    } else {
        ap_return_10 = ap_return_10_preg.read();
    }
}

void relu::thread_ap_return_11() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_11 = select_ln81_11_fu_520_p3.read();
    } else {
        ap_return_11 = ap_return_11_preg.read();
    }
}

void relu::thread_ap_return_12() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_12 = select_ln81_12_fu_538_p3.read();
    } else {
        ap_return_12 = ap_return_12_preg.read();
    }
}

void relu::thread_ap_return_13() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_13 = select_ln81_13_fu_556_p3.read();
    } else {
        ap_return_13 = ap_return_13_preg.read();
    }
}

void relu::thread_ap_return_14() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_14 = select_ln81_14_fu_574_p3.read();
    } else {
        ap_return_14 = ap_return_14_preg.read();
    }
}

void relu::thread_ap_return_15() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_15 = select_ln81_15_fu_592_p3.read();
    } else {
        ap_return_15 = ap_return_15_preg.read();
    }
}

void relu::thread_ap_return_16() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_16 = select_ln81_16_fu_610_p3.read();
    } else {
        ap_return_16 = ap_return_16_preg.read();
    }
}

void relu::thread_ap_return_17() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_17 = select_ln81_17_fu_628_p3.read();
    } else {
        ap_return_17 = ap_return_17_preg.read();
    }
}

void relu::thread_ap_return_18() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_18 = select_ln81_18_fu_646_p3.read();
    } else {
        ap_return_18 = ap_return_18_preg.read();
    }
}

void relu::thread_ap_return_19() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_19 = select_ln81_19_fu_664_p3.read();
    } else {
        ap_return_19 = ap_return_19_preg.read();
    }
}

void relu::thread_ap_return_2() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_2 = select_ln81_2_fu_358_p3.read();
    } else {
        ap_return_2 = ap_return_2_preg.read();
    }
}

void relu::thread_ap_return_20() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_20 = select_ln81_20_fu_682_p3.read();
    } else {
        ap_return_20 = ap_return_20_preg.read();
    }
}

void relu::thread_ap_return_21() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_21 = select_ln81_21_fu_700_p3.read();
    } else {
        ap_return_21 = ap_return_21_preg.read();
    }
}

void relu::thread_ap_return_22() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_22 = select_ln81_22_fu_718_p3.read();
    } else {
        ap_return_22 = ap_return_22_preg.read();
    }
}

void relu::thread_ap_return_23() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_23 = select_ln81_23_fu_736_p3.read();
    } else {
        ap_return_23 = ap_return_23_preg.read();
    }
}

void relu::thread_ap_return_24() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_24 = select_ln81_24_fu_754_p3.read();
    } else {
        ap_return_24 = ap_return_24_preg.read();
    }
}

void relu::thread_ap_return_25() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_25 = select_ln81_25_fu_772_p3.read();
    } else {
        ap_return_25 = ap_return_25_preg.read();
    }
}

void relu::thread_ap_return_26() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_26 = select_ln81_26_fu_790_p3.read();
    } else {
        ap_return_26 = ap_return_26_preg.read();
    }
}

void relu::thread_ap_return_27() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_27 = select_ln81_27_fu_808_p3.read();
    } else {
        ap_return_27 = ap_return_27_preg.read();
    }
}

void relu::thread_ap_return_28() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_28 = select_ln81_28_fu_826_p3.read();
    } else {
        ap_return_28 = ap_return_28_preg.read();
    }
}

void relu::thread_ap_return_29() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_29 = select_ln81_29_fu_844_p3.read();
    } else {
        ap_return_29 = ap_return_29_preg.read();
    }
}

void relu::thread_ap_return_3() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_3 = select_ln81_3_fu_376_p3.read();
    } else {
        ap_return_3 = ap_return_3_preg.read();
    }
}

void relu::thread_ap_return_30() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_30 = select_ln81_30_fu_862_p3.read();
    } else {
        ap_return_30 = ap_return_30_preg.read();
    }
}

void relu::thread_ap_return_31() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_31 = select_ln81_31_fu_880_p3.read();
    } else {
        ap_return_31 = ap_return_31_preg.read();
    }
}

void relu::thread_ap_return_32() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_32 = select_ln81_32_fu_898_p3.read();
    } else {
        ap_return_32 = ap_return_32_preg.read();
    }
}

void relu::thread_ap_return_33() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_33 = select_ln81_33_fu_916_p3.read();
    } else {
        ap_return_33 = ap_return_33_preg.read();
    }
}

void relu::thread_ap_return_34() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_34 = select_ln81_34_fu_934_p3.read();
    } else {
        ap_return_34 = ap_return_34_preg.read();
    }
}

void relu::thread_ap_return_35() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_35 = select_ln81_35_fu_952_p3.read();
    } else {
        ap_return_35 = ap_return_35_preg.read();
    }
}

void relu::thread_ap_return_4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_4 = select_ln81_4_fu_394_p3.read();
    } else {
        ap_return_4 = ap_return_4_preg.read();
    }
}

void relu::thread_ap_return_5() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_5 = select_ln81_5_fu_412_p3.read();
    } else {
        ap_return_5 = ap_return_5_preg.read();
    }
}

void relu::thread_ap_return_6() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_6 = select_ln81_6_fu_430_p3.read();
    } else {
        ap_return_6 = ap_return_6_preg.read();
    }
}

void relu::thread_ap_return_7() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_7 = select_ln81_7_fu_448_p3.read();
    } else {
        ap_return_7 = ap_return_7_preg.read();
    }
}

void relu::thread_ap_return_8() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_8 = select_ln81_8_fu_466_p3.read();
    } else {
        ap_return_8 = ap_return_8_preg.read();
    }
}

void relu::thread_ap_return_9() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        ap_return_9 = select_ln81_9_fu_484_p3.read();
    } else {
        ap_return_9 = ap_return_9_preg.read();
    }
}

void relu::thread_icmp_ln1494_10_fu_496_p2() {
    icmp_ln1494_10_fu_496_p2 = (!data_10_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_10_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_11_fu_514_p2() {
    icmp_ln1494_11_fu_514_p2 = (!data_11_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_11_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_12_fu_532_p2() {
    icmp_ln1494_12_fu_532_p2 = (!data_12_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_12_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_13_fu_550_p2() {
    icmp_ln1494_13_fu_550_p2 = (!data_13_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_13_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_14_fu_568_p2() {
    icmp_ln1494_14_fu_568_p2 = (!data_14_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_14_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_15_fu_586_p2() {
    icmp_ln1494_15_fu_586_p2 = (!data_15_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_15_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_16_fu_604_p2() {
    icmp_ln1494_16_fu_604_p2 = (!data_16_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_16_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_17_fu_622_p2() {
    icmp_ln1494_17_fu_622_p2 = (!data_17_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_17_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_18_fu_640_p2() {
    icmp_ln1494_18_fu_640_p2 = (!data_18_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_18_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_19_fu_658_p2() {
    icmp_ln1494_19_fu_658_p2 = (!data_19_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_19_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_1_fu_334_p2() {
    icmp_ln1494_1_fu_334_p2 = (!data_1_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_1_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_20_fu_676_p2() {
    icmp_ln1494_20_fu_676_p2 = (!data_20_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_20_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_21_fu_694_p2() {
    icmp_ln1494_21_fu_694_p2 = (!data_21_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_21_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_22_fu_712_p2() {
    icmp_ln1494_22_fu_712_p2 = (!data_22_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_22_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_23_fu_730_p2() {
    icmp_ln1494_23_fu_730_p2 = (!data_23_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_23_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_24_fu_748_p2() {
    icmp_ln1494_24_fu_748_p2 = (!data_24_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_24_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_25_fu_766_p2() {
    icmp_ln1494_25_fu_766_p2 = (!data_25_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_25_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_26_fu_784_p2() {
    icmp_ln1494_26_fu_784_p2 = (!data_26_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_26_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_27_fu_802_p2() {
    icmp_ln1494_27_fu_802_p2 = (!data_27_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_27_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_28_fu_820_p2() {
    icmp_ln1494_28_fu_820_p2 = (!data_28_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_28_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_29_fu_838_p2() {
    icmp_ln1494_29_fu_838_p2 = (!data_29_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_29_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_2_fu_352_p2() {
    icmp_ln1494_2_fu_352_p2 = (!data_2_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_2_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_30_fu_856_p2() {
    icmp_ln1494_30_fu_856_p2 = (!data_30_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_30_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_31_fu_874_p2() {
    icmp_ln1494_31_fu_874_p2 = (!data_31_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_31_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_32_fu_892_p2() {
    icmp_ln1494_32_fu_892_p2 = (!data_32_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_32_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_33_fu_910_p2() {
    icmp_ln1494_33_fu_910_p2 = (!data_33_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_33_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_34_fu_928_p2() {
    icmp_ln1494_34_fu_928_p2 = (!data_34_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_34_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_35_fu_946_p2() {
    icmp_ln1494_35_fu_946_p2 = (!data_35_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_35_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_3_fu_370_p2() {
    icmp_ln1494_3_fu_370_p2 = (!data_3_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_3_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_4_fu_388_p2() {
    icmp_ln1494_4_fu_388_p2 = (!data_4_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_4_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_5_fu_406_p2() {
    icmp_ln1494_5_fu_406_p2 = (!data_5_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_5_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_6_fu_424_p2() {
    icmp_ln1494_6_fu_424_p2 = (!data_6_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_6_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_7_fu_442_p2() {
    icmp_ln1494_7_fu_442_p2 = (!data_7_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_7_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_8_fu_460_p2() {
    icmp_ln1494_8_fu_460_p2 = (!data_8_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_8_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_9_fu_478_p2() {
    icmp_ln1494_9_fu_478_p2 = (!data_9_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_9_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_icmp_ln1494_fu_316_p2() {
    icmp_ln1494_fu_316_p2 = (!data_0_V_read.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(data_0_V_read.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void relu::thread_select_ln81_10_fu_502_p3() {
    select_ln81_10_fu_502_p3 = (!icmp_ln1494_10_fu_496_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_10_fu_496_p2.read()[0].to_bool())? trunc_ln1494_10_fu_492_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_11_fu_520_p3() {
    select_ln81_11_fu_520_p3 = (!icmp_ln1494_11_fu_514_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_11_fu_514_p2.read()[0].to_bool())? trunc_ln1494_11_fu_510_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_12_fu_538_p3() {
    select_ln81_12_fu_538_p3 = (!icmp_ln1494_12_fu_532_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_12_fu_532_p2.read()[0].to_bool())? trunc_ln1494_12_fu_528_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_13_fu_556_p3() {
    select_ln81_13_fu_556_p3 = (!icmp_ln1494_13_fu_550_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_13_fu_550_p2.read()[0].to_bool())? trunc_ln1494_13_fu_546_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_14_fu_574_p3() {
    select_ln81_14_fu_574_p3 = (!icmp_ln1494_14_fu_568_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_14_fu_568_p2.read()[0].to_bool())? trunc_ln1494_14_fu_564_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_15_fu_592_p3() {
    select_ln81_15_fu_592_p3 = (!icmp_ln1494_15_fu_586_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_15_fu_586_p2.read()[0].to_bool())? trunc_ln1494_15_fu_582_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_16_fu_610_p3() {
    select_ln81_16_fu_610_p3 = (!icmp_ln1494_16_fu_604_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_16_fu_604_p2.read()[0].to_bool())? trunc_ln1494_16_fu_600_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_17_fu_628_p3() {
    select_ln81_17_fu_628_p3 = (!icmp_ln1494_17_fu_622_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_17_fu_622_p2.read()[0].to_bool())? trunc_ln1494_17_fu_618_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_18_fu_646_p3() {
    select_ln81_18_fu_646_p3 = (!icmp_ln1494_18_fu_640_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_18_fu_640_p2.read()[0].to_bool())? trunc_ln1494_18_fu_636_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_19_fu_664_p3() {
    select_ln81_19_fu_664_p3 = (!icmp_ln1494_19_fu_658_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_19_fu_658_p2.read()[0].to_bool())? trunc_ln1494_19_fu_654_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_1_fu_340_p3() {
    select_ln81_1_fu_340_p3 = (!icmp_ln1494_1_fu_334_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_1_fu_334_p2.read()[0].to_bool())? trunc_ln1494_1_fu_330_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_20_fu_682_p3() {
    select_ln81_20_fu_682_p3 = (!icmp_ln1494_20_fu_676_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_20_fu_676_p2.read()[0].to_bool())? trunc_ln1494_20_fu_672_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_21_fu_700_p3() {
    select_ln81_21_fu_700_p3 = (!icmp_ln1494_21_fu_694_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_21_fu_694_p2.read()[0].to_bool())? trunc_ln1494_21_fu_690_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_22_fu_718_p3() {
    select_ln81_22_fu_718_p3 = (!icmp_ln1494_22_fu_712_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_22_fu_712_p2.read()[0].to_bool())? trunc_ln1494_22_fu_708_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_23_fu_736_p3() {
    select_ln81_23_fu_736_p3 = (!icmp_ln1494_23_fu_730_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_23_fu_730_p2.read()[0].to_bool())? trunc_ln1494_23_fu_726_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_24_fu_754_p3() {
    select_ln81_24_fu_754_p3 = (!icmp_ln1494_24_fu_748_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_24_fu_748_p2.read()[0].to_bool())? trunc_ln1494_24_fu_744_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_25_fu_772_p3() {
    select_ln81_25_fu_772_p3 = (!icmp_ln1494_25_fu_766_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_25_fu_766_p2.read()[0].to_bool())? trunc_ln1494_25_fu_762_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_26_fu_790_p3() {
    select_ln81_26_fu_790_p3 = (!icmp_ln1494_26_fu_784_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_26_fu_784_p2.read()[0].to_bool())? trunc_ln1494_26_fu_780_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_27_fu_808_p3() {
    select_ln81_27_fu_808_p3 = (!icmp_ln1494_27_fu_802_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_27_fu_802_p2.read()[0].to_bool())? trunc_ln1494_27_fu_798_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_28_fu_826_p3() {
    select_ln81_28_fu_826_p3 = (!icmp_ln1494_28_fu_820_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_28_fu_820_p2.read()[0].to_bool())? trunc_ln1494_28_fu_816_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_29_fu_844_p3() {
    select_ln81_29_fu_844_p3 = (!icmp_ln1494_29_fu_838_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_29_fu_838_p2.read()[0].to_bool())? trunc_ln1494_29_fu_834_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_2_fu_358_p3() {
    select_ln81_2_fu_358_p3 = (!icmp_ln1494_2_fu_352_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_2_fu_352_p2.read()[0].to_bool())? trunc_ln1494_2_fu_348_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_30_fu_862_p3() {
    select_ln81_30_fu_862_p3 = (!icmp_ln1494_30_fu_856_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_30_fu_856_p2.read()[0].to_bool())? trunc_ln1494_30_fu_852_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_31_fu_880_p3() {
    select_ln81_31_fu_880_p3 = (!icmp_ln1494_31_fu_874_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_31_fu_874_p2.read()[0].to_bool())? trunc_ln1494_31_fu_870_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_32_fu_898_p3() {
    select_ln81_32_fu_898_p3 = (!icmp_ln1494_32_fu_892_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_32_fu_892_p2.read()[0].to_bool())? trunc_ln1494_32_fu_888_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_33_fu_916_p3() {
    select_ln81_33_fu_916_p3 = (!icmp_ln1494_33_fu_910_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_33_fu_910_p2.read()[0].to_bool())? trunc_ln1494_33_fu_906_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_34_fu_934_p3() {
    select_ln81_34_fu_934_p3 = (!icmp_ln1494_34_fu_928_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_34_fu_928_p2.read()[0].to_bool())? trunc_ln1494_34_fu_924_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_35_fu_952_p3() {
    select_ln81_35_fu_952_p3 = (!icmp_ln1494_35_fu_946_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_35_fu_946_p2.read()[0].to_bool())? trunc_ln1494_35_fu_942_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_3_fu_376_p3() {
    select_ln81_3_fu_376_p3 = (!icmp_ln1494_3_fu_370_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_3_fu_370_p2.read()[0].to_bool())? trunc_ln1494_3_fu_366_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_4_fu_394_p3() {
    select_ln81_4_fu_394_p3 = (!icmp_ln1494_4_fu_388_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_4_fu_388_p2.read()[0].to_bool())? trunc_ln1494_4_fu_384_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_5_fu_412_p3() {
    select_ln81_5_fu_412_p3 = (!icmp_ln1494_5_fu_406_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_5_fu_406_p2.read()[0].to_bool())? trunc_ln1494_5_fu_402_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_6_fu_430_p3() {
    select_ln81_6_fu_430_p3 = (!icmp_ln1494_6_fu_424_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_6_fu_424_p2.read()[0].to_bool())? trunc_ln1494_6_fu_420_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_7_fu_448_p3() {
    select_ln81_7_fu_448_p3 = (!icmp_ln1494_7_fu_442_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_7_fu_442_p2.read()[0].to_bool())? trunc_ln1494_7_fu_438_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_8_fu_466_p3() {
    select_ln81_8_fu_466_p3 = (!icmp_ln1494_8_fu_460_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_8_fu_460_p2.read()[0].to_bool())? trunc_ln1494_8_fu_456_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_9_fu_484_p3() {
    select_ln81_9_fu_484_p3 = (!icmp_ln1494_9_fu_478_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_9_fu_478_p2.read()[0].to_bool())? trunc_ln1494_9_fu_474_p1.read(): ap_const_lv11_0);
}

void relu::thread_select_ln81_fu_322_p3() {
    select_ln81_fu_322_p3 = (!icmp_ln1494_fu_316_p2.read()[0].is_01())? sc_lv<11>(): ((icmp_ln1494_fu_316_p2.read()[0].to_bool())? trunc_ln1494_fu_312_p1.read(): ap_const_lv11_0);
}

void relu::thread_trunc_ln1494_10_fu_492_p1() {
    trunc_ln1494_10_fu_492_p1 = data_10_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_11_fu_510_p1() {
    trunc_ln1494_11_fu_510_p1 = data_11_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_12_fu_528_p1() {
    trunc_ln1494_12_fu_528_p1 = data_12_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_13_fu_546_p1() {
    trunc_ln1494_13_fu_546_p1 = data_13_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_14_fu_564_p1() {
    trunc_ln1494_14_fu_564_p1 = data_14_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_15_fu_582_p1() {
    trunc_ln1494_15_fu_582_p1 = data_15_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_16_fu_600_p1() {
    trunc_ln1494_16_fu_600_p1 = data_16_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_17_fu_618_p1() {
    trunc_ln1494_17_fu_618_p1 = data_17_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_18_fu_636_p1() {
    trunc_ln1494_18_fu_636_p1 = data_18_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_19_fu_654_p1() {
    trunc_ln1494_19_fu_654_p1 = data_19_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_1_fu_330_p1() {
    trunc_ln1494_1_fu_330_p1 = data_1_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_20_fu_672_p1() {
    trunc_ln1494_20_fu_672_p1 = data_20_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_21_fu_690_p1() {
    trunc_ln1494_21_fu_690_p1 = data_21_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_22_fu_708_p1() {
    trunc_ln1494_22_fu_708_p1 = data_22_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_23_fu_726_p1() {
    trunc_ln1494_23_fu_726_p1 = data_23_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_24_fu_744_p1() {
    trunc_ln1494_24_fu_744_p1 = data_24_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_25_fu_762_p1() {
    trunc_ln1494_25_fu_762_p1 = data_25_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_26_fu_780_p1() {
    trunc_ln1494_26_fu_780_p1 = data_26_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_27_fu_798_p1() {
    trunc_ln1494_27_fu_798_p1 = data_27_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_28_fu_816_p1() {
    trunc_ln1494_28_fu_816_p1 = data_28_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_29_fu_834_p1() {
    trunc_ln1494_29_fu_834_p1 = data_29_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_2_fu_348_p1() {
    trunc_ln1494_2_fu_348_p1 = data_2_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_30_fu_852_p1() {
    trunc_ln1494_30_fu_852_p1 = data_30_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_31_fu_870_p1() {
    trunc_ln1494_31_fu_870_p1 = data_31_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_32_fu_888_p1() {
    trunc_ln1494_32_fu_888_p1 = data_32_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_33_fu_906_p1() {
    trunc_ln1494_33_fu_906_p1 = data_33_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_34_fu_924_p1() {
    trunc_ln1494_34_fu_924_p1 = data_34_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_35_fu_942_p1() {
    trunc_ln1494_35_fu_942_p1 = data_35_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_3_fu_366_p1() {
    trunc_ln1494_3_fu_366_p1 = data_3_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_4_fu_384_p1() {
    trunc_ln1494_4_fu_384_p1 = data_4_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_5_fu_402_p1() {
    trunc_ln1494_5_fu_402_p1 = data_5_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_6_fu_420_p1() {
    trunc_ln1494_6_fu_420_p1 = data_6_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_7_fu_438_p1() {
    trunc_ln1494_7_fu_438_p1 = data_7_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_8_fu_456_p1() {
    trunc_ln1494_8_fu_456_p1 = data_8_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_9_fu_474_p1() {
    trunc_ln1494_9_fu_474_p1 = data_9_V_read.read().range(11-1, 0);
}

void relu::thread_trunc_ln1494_fu_312_p1() {
    trunc_ln1494_fu_312_p1 = data_0_V_read.read().range(11-1, 0);
}

void relu::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

